# Projeto para departamento de Recursos Humanos - Triagem e Análise de currículos

## Instalação de bibliotecas

In [2]:
!pip install langchain-groq langchain-community langchain-core PyMuPDF

Requirement already satisfied: langchain-groq in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (1.1.2)
Requirement already satisfied: langchain-community in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (0.4.2)
Requirement already satisfied: langchain-core in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (1.4.0)
Requirement already satisfied: PyMuPDF in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (1.27.2.3)
Requirement already satisfied: groq<1.0.0,>=0.30.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from langchain-groq) (0.37.1)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from langchain-community) (3.14.0)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from langchain-community) (0.4.3)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.7 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from langchain-community) (1.0.7)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from langchain-community) (0.8.9)
Requirement already satisfied: numpy>=1.26.2 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from langchain-community) (2.4.6)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from langchain-community) (2.14.1)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from langchain-community) (6.0.3)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from langchain-community) (2.34.2)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from langchain-community) (2.0.50)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from langchain-community) (9.1.4)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from langchain-core) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.14 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from langchain-core) (0.0.16)
Requirement already satisfied: packaging>=23.2.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from langchain-core) (26.2)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from langchain-core) (2.13.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from langchain-core) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from langchain-core) (0.16.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.24.2)
Requirement already satisfied: anyio<5,>=3.5.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (0.28.1)
Requirement already satisfied: sniffio in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.3.1)
Requirement already satisfied: jsonpointer>=1.9 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core) (3.1.1)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.2 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from langchain-classic<2.0.0,>=1.0.7->langchain-community) (1.1.2)
Requirement already satisfied: orjson>=3.9.14 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: websockets>=15.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (15.0.1)
Requirement already satisfied: xxhash>=3.0.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.7.0)
Requirement already satisfied: zstandard>=0.23.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2026.5.20)
Requirement already satisfied: greenlet>=1 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-community) (3.5.1)
Requirement already satisfied: httpcore==1.* in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from httpx<1,>=0.23.0->groq<1.0.0,>=0.30.0->langchain-groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq<1.0.0,>=0.30.0->langchain-groq) (0.16.0)

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

## Carregando os documentos - Somente Google Colab

In [3]:
from google.colab import files
uploaded = files.upload()
file_path = list(uploaded.keys())[0]
print(f"Arquivo carregado: " {file_path})

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3783758657.py, line 4)

## Extração de conteúdos

In [4]:
import os
import fitz # PyMuPDF

path = "Currículo1.pdf"

def extract_text_pdf(filepath):
    doc = fitz.open(filepath)
    text = ""
    for page in doc:
        text += page.get_text()
    doc.close()
    return text.strip()

In [5]:
extract_text_pdf(path)

'CURRICULUM VITAE \nTHOMAS A. ANDERSON\u200b\n ✉ thomas.anderson@email.com\u200b\n ▷ linkedin.com/in/thomasanderson\u200b\n ▷ github.com/thomasanderson-dev \n \n \nOBJETIVO \nProfissional de tecnologia com 5 anos de experiência em desenvolvimento de \nsoftware e análise de dados, buscando ingressar no curso de Pós-Graduação em \nCiência de Dados e Inteligência Artificial para ampliar conhecimentos em machine \nlearning e big data. Comprometido em aplicar habilidades técnicas em projetos \ninovadores e contribuir para soluções orientadas por dados. \n \nFORMAÇÃO ACADÊMICA \nBacharelado em Ciência da Computação\u200b\nUniversidade de São Paulo (USP) – São Paulo, SP\u200b\nFev 2018 – Dez 2022 \n●\u200b TCC: “Otimização de Algoritmos de Machine Learning para Previsão de \nDemanda em Varejo”. \n●\u200b Participação em grupo de pesquisa em inteligência artificial. \n \nEXPERIÊNCIA PROFISSIONAL \nEngenheiro de Software Júnior | TechSolutions Brasil\u200b\nJan 2023 – Atual \n●\u200b Desenvolvimento de APIs em Python e Node.js para integração de sistemas \nde gestão empresarial. \n●\u200b Implementação de testes automatizados, reduzindo bugs em produção em \n30%. \n●\u200b Colaboração em equipes ágeis (Scrum) para entrega de projetos em cloud \n(AWS). \nEstagiário em Análise de Dados | InovaData Analytics\u200b\nMar 2021 – Dez 2022 \n●\u200b Criação de dashboards em Power BI para monitoramento de KPIs de vendas. \n●\u200b Processamento de datasets com Pandas e SQL, identificando insights para \nredução de custos. \n●\u200b Automação de relatórios mensais, economizando 15 horas mensais da \nequipe. \nDesenvolvedor Full-Stack Freelancer\u200b\nJun 2020 – Fev 2021 \n●\u200b Construção de aplicações web com React e Django para clientes de \ne-commerce. \n●\u200b Integração de sistemas de pagamento (PagSeguro, Mercado Pago). \n \nHABILIDADES TÉCNICAS \n●\u200b Linguagens: Python, Java, JavaScript, SQL \n●\u200b Frameworks: React, Node.js, Django \n●\u200b Banco de Dados: MySQL, MongoDB, PostgreSQL \n●\u200b Ferramentas: Git, Docker, Jupyter Notebook, Power BI \n●\u200b Cloud: AWS (EC2, S3), Google Cloud Platform \n●\u200b Análise de Dados: Pandas, NumPy, Tableau \n \nCERTIFICAÇÕES \n●\u200b Certificado AWS Certified Developer – Associate (2023) \n●\u200b Scrum Master Certified (SMC) – CertiProf (2022) \n●\u200b Google Data Analytics Professional Certificate (2021) \n \nIDIOMAS \n●\u200b Português: Nativo \n●\u200b Inglês: Avançado (TOEFL: 92/120) \n●\u200b Espanhol: Intermediário \n \nPROJETOS RELEVANTES \nSistema de Recomendação para E-commerce \n●\u200b Desenvolvimento de modelo de ML em Python para personalizar sugestões \nde produtos, aumentando conversões em 18%. \nPlataforma de Gestão de Projetos \n●\u200b Aplicação web full-stack (React + Django) para gestão de tarefas, utilizada \npor 500+ usuários. \n \n \nINFORMAÇÕES ADICIONAIS \n●\u200b Interesses: Inteligência Artificial, Big Data, Metodologias Ágeis. \n●\u200b Voluntariado: Instrutor de programação para jovens em ONGs locais \n(2022–Atual). \n●\u200b Hobbies: Leitura sobre inovação tecnológica, maratonas de hackathon, \nciclismo.'

In [6]:
extract_text_pdf("Currículo2.pdf")

'Ana Clara Santos\u200b\nE-mail: ana.santos@techfict.com.br\u200b\nLinkedIn: linkedin.com/in/ana-clara-santos-dev\u200b\nPortfólio: anasantos-dev.com   \n \nOBJETIVO \nProfissional com 4 anos de experiência em desenvolvimento de software, \nespecializada em soluções web completas, buscando aprimorar conhecimentos em \ntecnologias emergentes por meio de cursos avançados. Interesse em integrar \ninovação técnica com boas práticas de UX/UI para criar sistemas escaláveis e \nintuitivos. \n \nFORMAÇÃO ACADÊMICA \nBacharelado em Sistemas de Informação\u200b\nPontifícia Universidade Católica do Rio de Janeiro (PUC-Rio) – Rio de Janeiro, RJ\u200b\nMar 2017 – Dez 2021 \n●\u200b Bolsista do programa de iniciação científica em desenvolvimento ágil. \n●\u200b TCC: "Framework para otimização de performance em aplicações React". \nCurso Técnico em Informática\u200b\nEscola Técnica Estadual do Rio de Janeiro (FAETEC)\u200b\nFev 2014 – Dez 2016 \n \nEXPERIÊNCIA PROFISSIONAL \nDesenvolvedora de Software | NexTech Solutions\u200b\nMar 2022 – Atual \n●\u200b Liderança técnica no desenvolvimento de uma plataforma de gestão de \nclientes utilizando React (front-end) e Spring Boot (back-end). \n●\u200b Integração de microsserviços com Docker e Kubernetes, reduzindo tempo de \ndeploy em 25%. \n●\u200b Refatoração de código legado, melhorando a manutenibilidade e \ndocumentação do sistema. \nEstagiária Full Stack | StartUpLab\u200b\nAgo 2020 – Fev 2022 \n●\u200b Desenvolvimento de MVP para startup de edtech utilizando Vue.js e Node.js. \n●\u200b Configuração de pipelines CI/CD com GitHub Actions. \n●\u200b Implementação de autenticação JWT e integração com APIs de terceiros \n(Google Classroom). \nFreelancer em Desenvolvimento Web\u200b\nJan 2019 – Jul 2020 \n●\u200b Criação de sites responsivos para pequenos negócios usando HTML/CSS, \nJavaScript e WordPress. \n●\u200b Otimização de SEO, aumentando tráfego orgânico em até 40% para clientes. \n \nHABILIDADES TÉCNICAS \n●\u200b Front-end: React, Vue.js, TypeScript, Tailwind CSS \n●\u200b Back-end: Node.js, Java (Spring Boot), Python (Django) \n●\u200b Banco de Dados: PostgreSQL, Firebase, Redis \n●\u200b DevOps: Docker, Kubernetes, AWS (Lambda, RDS), Jenkins \n●\u200b Testes: Jest, Cypress, Selenium \n●\u200b Ferramentas: Figma (prototipagem), Postman, VS Code \n \nCERTIFICAÇÕES \n●\u200b Oracle Certified Professional: Java SE 11 Developer (2023) \n●\u200b Microsoft Certified: Azure Fundamentals (2022) \n●\u200b Certificação Scrum Foundation (2021) \n \nIDIOMAS \n●\u200b Português: Nativo \n●\u200b Inglês: Fluente (IELTS: 7.5) \n●\u200b Francês: Básico \n \nPROJETOS DESTACADOS \nPlataforma de Agendamento Médico \n●\u200b Full-stack: React + Django REST. Integração com Twilio para SMS e Google \nCalendar API. \n●\u200b Projeto open-source com 1.2k estrelas no GitHub. \nAplicativo de Gestão Financeira Pessoal \n●\u200b Mobile-first (PWA) com Vue.js e Firebase. Recursos de gráficos dinâmicos via \nChart.js. \n \nINFORMAÇÕES ADICIONAIS \n●\u200b Mentoria: Organizadora de workshops gratuitos sobre carreira em TI para \nmulheres (Projeto DevElas). \n●\u200b Premiações: 1º lugar no Hackathon RioTech 2022 com projeto de \nacessibilidade digital. \n●\u200b Interesses: Open source, UX/UI design, sustentabilidade aplicada à \ntecnologia.'

## Parsing de documentos com Docling

In [7]:
!pip install rapidocr_onnxruntime opencv-python docling

Requirement already satisfied: rapidocr_onnxruntime in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (1.4.4)
Requirement already satisfied: opencv-python in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (4.13.0.92)
Requirement already satisfied: docling in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (2.106.0)
Requirement already satisfied: pyclipper>=1.2.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from rapidocr_onnxruntime) (1.4.0)
Requirement already satisfied: numpy<3.0.0,>=1.19.5 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from rapidocr_onnxruntime) (2.4.6)
Requirement already satisfied: six>=1.15.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from rapidocr_onnxruntime) (1.17.0)
Requirement already satisfied: Shapely!=2.0.4,>=1.7.1 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from rapidocr_onnxruntime) (2.1.2)
Requirement already satisfied: PyYAML in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from rapidocr_onnxruntime) (6.0.3)
Requirement already satisfied: Pillow in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from rapidocr_onnxruntime) (12.2.0)
Requirement already satisfied: onnxruntime>=1.7.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from rapidocr_onnxruntime) (1.27.0)
Requirement already satisfied: tqdm in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from rapidocr_onnxruntime) (4.68.1)
Requirement already satisfied: docling-slim==2.106.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (2.106.0)
Requirement already satisfied: certifi>=2024.7.4 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim==2.106.0->docling-slim[standard]==2.106.0->docling) (2026.5.20)
Requirement already satisfied: docling-core<3.0.0,>=2.83.1 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim==2.106.0->docling-slim[standard]==2.106.0->docling) (2.84.0)
Requirement already satisfied: filetype<2.0.0,>=1.2.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim==2.106.0->docling-slim[standard]==2.106.0->docling) (1.2.0)
Requirement already satisfied: pluggy<2.0.0,>=1.0.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim==2.106.0->docling-slim[standard]==2.106.0->docling) (1.6.0)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.3.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim==2.106.0->docling-slim[standard]==2.106.0->docling) (2.14.1)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim==2.106.0->docling-slim[standard]==2.106.0->docling) (2.13.4)
Requirement already satisfied: requests<3.0.0,>=2.32.2 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim==2.106.0->docling-slim[standard]==2.106.0->docling) (2.34.2)
Requirement already satisfied: accelerate<2,>=1.0.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (1.14.0)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.12.3 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (4.14.3)
Requirement already satisfied: defusedxml<0.8.0,>=0.7.1 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (0.7.1)
Requirement already satisfied: docling-ibm-models<4,>=3.13.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (3.13.3)
Requirement already satisfied: docling-parse<8.0.0,>=7.0.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (7.0.0)
Requirement already satisfied: httpx<1.0.0,>=0.28 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (0.28.1)
Requirement already satisfied: huggingface-hub<2,>=0.23 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (1.19.0)
Requirement already satisfied: lxml<7.0.0,>=4.0.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (6.1.1)
Requirement already satisfied: mail-parser<5.0.0,>=4.1.4 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (4.4.0)
Requirement already satisfied: marko<3.0.0,>=2.1.2 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (2.2.3)
Requirement already satisfied: openpyxl<4.0.0,>=3.1.5 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (3.1.5)
Requirement already satisfied: polyfactory>=2.22.2 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (3.3.0)
Requirement already satisfied: pylatexenc<3.0,>=2.10 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (2.10)
Requirement already satisfied: pypdfium2!=4.30.1,<6.0.0,>=4.30.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (5.10.1)
Requirement already satisfied: python-docx<2.0.0,>=1.1.2 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (1.2.0)
Requirement already satisfied: python-dotenv~=1.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (1.2.2)
Requirement already satisfied: python-pptx<2.0.0,>=1.0.2 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (1.0.2)
Requirement already satisfied: rapidocr<4.0.0,>=3.8 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (3.9.0)
Requirement already satisfied: rich>=13.0.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (15.0.0)
Requirement already satisfied: rtree<2.0.0,>=1.3.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (1.4.1)
Requirement already satisfied: scipy<2.0.0,>=1.6.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (1.17.1)
Requirement already satisfied: torch<3.0.0,>=2.2.2 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (2.12.0)
Requirement already satisfied: torchvision<1,>=0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (0.27.0)
Requirement already satisfied: typer<0.27.0,>=0.12.5 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (0.24.2)
Requirement already satisfied: websockets<17.0,>=14.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-slim[standard]==2.106.0->docling) (15.0.1)
Requirement already satisfied: flatbuffers in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from onnxruntime>=1.7.0->rapidocr_onnxruntime) (25.12.19)
Requirement already satisfied: packaging in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from onnxruntime>=1.7.0->rapidocr_onnxruntime) (26.2)
Requirement already satisfied: protobuf>=4.25.8 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from onnxruntime>=1.7.0->rapidocr_onnxruntime) (7.35.0)
Requirement already satisfied: psutil in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from accelerate<2,>=1.0.0->docling-slim[standard]==2.106.0->docling) (7.2.2)
Requirement already satisfied: safetensors>=0.4.3 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from accelerate<2,>=1.0.0->docling-slim[standard]==2.106.0->docling) (0.8.0)
Requirement already satisfied: soupsieve>=1.6.1 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from beautifulsoup4<5.0.0,>=4.12.3->docling-slim[standard]==2.106.0->docling) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from beautifulsoup4<5.0.0,>=4.12.3->docling-slim[standard]==2.106.0->docling) (4.15.0)
Requirement already satisfied: jsonschema<5.0.0,>=4.16.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-core<3.0.0,>=2.83.1->docling-slim==2.106.0->docling-slim[standard]==2.106.0->docling) (4.26.0)
Requirement already satisfied: jsonref<2.0.0,>=1.1.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-core<3.0.0,>=2.83.1->docling-slim==2.106.0->docling-slim[standard]==2.106.0->docling) (1.1.0)
Requirement already satisfied: tabulate<0.11.0,>=0.9.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-core<3.0.0,>=2.83.1->docling-slim==2.106.0->docling-slim[standard]==2.106.0->docling) (0.10.0)
Requirement already satisfied: pandas<4.0.0,>=2.1.4 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-core<3.0.0,>=2.83.1->docling-slim==2.106.0->docling-slim[standard]==2.106.0->docling) (3.0.3)
Requirement already satisfied: latex2mathml<4.0.0,>=3.77.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-core<3.0.0,>=2.83.1->docling-slim==2.106.0->docling-slim[standard]==2.106.0->docling) (3.81.0)
Requirement already satisfied: semchunk<4.0.0,>=2.2.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-core[chunking]<3.0.0,>=2.73.0; extra == "standard"->docling-slim[standard]==2.106.0->docling) (3.2.5)
Requirement already satisfied: tree-sitter<0.27.0,>=0.25.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-core[chunking]<3.0.0,>=2.73.0; extra == "standard"->docling-slim[standard]==2.106.0->docling) (0.25.2)
Requirement already satisfied: tree-sitter-python>=0.23.6 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-core[chunking]<3.0.0,>=2.73.0; extra == "standard"->docling-slim[standard]==2.106.0->docling) (0.25.0)
Requirement already satisfied: tree-sitter-c>=0.23.4 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-core[chunking]<3.0.0,>=2.73.0; extra == "standard"->docling-slim[standard]==2.106.0->docling) (0.24.2)
Requirement already satisfied: tree-sitter-javascript>=0.23.1 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-core[chunking]<3.0.0,>=2.73.0; extra == "standard"->docling-slim[standard]==2.106.0->docling) (0.25.0)
Requirement already satisfied: tree-sitter-typescript>=0.23.2 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-core[chunking]<3.0.0,>=2.73.0; extra == "standard"->docling-slim[standard]==2.106.0->docling) (0.23.2)
Requirement already satisfied: transformers!=5.0.*,!=5.1.*,!=5.2.*,!=5.3.*,<6.0.0,>=4.34.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-core[chunking]<3.0.0,>=2.73.0; extra == "standard"->docling-slim[standard]==2.106.0->docling) (5.12.0)
Requirement already satisfied: jsonlines<5.0.0,>=3.1.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from docling-ibm-models<4,>=3.13.0->docling-slim[standard]==2.106.0->docling) (4.0.0)
Requirement already satisfied: anyio in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from httpx<1.0.0,>=0.28->docling-slim[standard]==2.106.0->docling) (4.13.0)
Requirement already satisfied: httpcore==1.* in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from httpx<1.0.0,>=0.28->docling-slim[standard]==2.106.0->docling) (1.0.9)
Requirement already satisfied: idna in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from httpx<1.0.0,>=0.28->docling-slim[standard]==2.106.0->docling) (3.18)
Requirement already satisfied: h11>=0.16 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from httpcore==1.*->httpx<1.0.0,>=0.28->docling-slim[standard]==2.106.0->docling) (0.16.0)
Requirement already satisfied: click>=8.4.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from huggingface-hub<2,>=0.23->docling-slim[standard]==2.106.0->docling) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from huggingface-hub<2,>=0.23->docling-slim[standard]==2.106.0->docling) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from huggingface-hub<2,>=0.23->docling-slim[standard]==2.106.0->docling) (2026.4.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from huggingface-hub<2,>=0.23->docling-slim[standard]==2.106.0->docling) (1.5.1)
Requirement already satisfied: et-xmlfile in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from openpyxl<4.0.0,>=3.1.5->docling-slim[standard]==2.106.0->docling) (2.0.0)
Requirement already satisfied: faker>=5.0.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from polyfactory>=2.22.2->docling-slim[standard]==2.106.0->docling) (40.23.0)
Requirement already satisfied: annotated-types>=0.6.0 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->docling-slim==2.106.0->docling-slim[standard]==2.106.0->docling) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->docling-slim==2.106.0->docling-slim[standard]==2.106.0->docling) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->docling-slim==2.106.0->docling-slim[standard]==2.106.0->docling) (0.4.2)
Requirement already satisfied: XlsxWriter>=0.5.7 in /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib64/python3.11/site-packages (from python-pptx<2.0.0,>=1.0.2->docling-slim[standard]==2.106.0->docling) (3.2.9)

In [8]:
from docling.document_converter import DocumentConverter

converter = DocumentConverter()
result = converter.convert(path)
print(result.document.export_to_markdown())

The plugin langchain_docling will not be loaded because Docling is being executed with allow_external_plugins=false.
The plugin langchain_docling will not be loaded because Docling is being executed with allow_external_plugins=false.
[INFO] 2026-06-28 18:49:07,859 [RapidOCR] base.py:23: Using engine_name: onnxruntime
[INFO] 2026-06-28 18:49:07,869 [RapidOCR] download_file.py:60: File exists and is valid: /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_det_small.onnx
[INFO] 2026-06-28 18:49:07,870 [RapidOCR] main.py:63: Using /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_det_small.onnx
[INFO] 2026-06-28 18:49:07,912 [RapidOCR] base.py:23: Using engine_name: onnxruntime
[INFO] 2026-06-28 18:49:07,914 [RapidOCR] download_file.py:60: File exists and is valid: /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-06-28 18:49:07,914 [RapidOCR] main.py:63: Using /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-06-28 18:49:07,943 [RapidOCR] base.py:23: Using engine_name: onnxruntime
[INFO] 2026-06-28 18:49:07,961 [RapidOCR] download_file.py:60: File exists and is valid: /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_rec_small.onnx
[INFO] 2026-06-28 18:49:07,962 [RapidOCR] main.py:63: Using /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_rec_small.onnx
The plugin langchain_docling will not be loaded because Docling is being executed with allow_external_plugins=false.

Loading weights:   0%|          | 0/770 [00:00<?, ?it/s]

The plugin langchain_docling will not be loaded because Docling is being executed with allow_external_plugins=false.

## THOMAS A. ANDERSON

- ✉ thomas.anderson@email.com
- ▷ linkedin.com/in/thomasanderson
- ▷ github.com/thomasanderson-dev

## OBJETIVO

Profissional de tecnologia com 5 anos de experiência em desenvolvimento de software e análise de dados, buscando ingressar no curso de Pós-Graduação em Ciência de Dados e Inteligência Artificial para ampliar conhecimentos em machine learning e big data. Comprometido em aplicar habilidades técnicas em projetos inovadores e contribuir para soluções orientadas por dados.

## FORMAÇÃO ACADÊMICA

## Bacharelado em Ciência da Computação

Universidade de São Paulo (USP) - São Paulo, SP Fev 2018 - Dez 2022

- TCC: 'Otimização de Algoritmos de Machine Learning para Previsão de Demanda em Varejo'.
- Participação em grupo de pesquisa em inteligência artificial.

## EXPERIÊNCIA PROFISSIONAL

## Engenheiro de Software Júnior | TechSolutions Brasil

Jan 2023 - Atual

- Desenvolvimento de APIs em Python e Node.js para integração de sistemas de gestão empresarial.
- Implementação de testes automatizados, reduzindo bugs em produção em 30%.
- Colaboração em equipes ágeis (Scrum) para entrega de projetos em cloud (AWS).

## Estagiário em Análise de Dados | InovaData Analytics

Mar 2021 - Dez 2022

- Criação de dashboards em Power BI para monitoramento de KPIs de vendas.
- Processamento de datasets com Pandas e SQL, identificando insights para redução de custos.
- Automação de relatórios mensais, economizando 15 horas mensais da equipe.

## Desenvolvedor Full-Stack Freelancer

## Jun 2020 - Fev 2021

- Construção de aplicações web com React e Django para clientes de e-commerce.
- Integração de sistemas de pagamento (PagSeguro, Mercado Pago).

## HABILIDADES TÉCNICAS

- Linguagens: Python, Java, JavaScript, SQL

- Frameworks: React, Node.js, Django

- Banco de Dados: MySQL, MongoDB, PostgreSQL

- Ferramentas: Git, Docker, Jupyter Notebook, Power BI

- Cloud: AWS (EC2, S3), Google Cloud Platform

- Análise de Dados: Pandas, NumPy, Tableau

## CERTIFICAÇÕES

- Certificado AWS Certified Developer - Associate (2023)
- Scrum Master Certified (SMC) - CertiProf (2022)
- Google Data Analytics Professional Certificate (2021)

## IDIOMAS

- ●

- Português: Nativo

- Inglês: Avançado (TOEFL: 92/120)

- ●

- Espanhol: Intermediário

## PROJETOS RELEVANTES

## Sistema de Recomendação para E-commerce

- Desenvolvimento de modelo de ML em Python para personalizar sugestões de produtos, aumentando conversões em 18%.

## Plataforma de Gestão de Projetos

- Aplicação web full-stack (React + Django) para gestão de tarefas, utilizada por 500+ usuários.

## INFORMAÇÕES ADICIONAIS

- Interesses: Inteligência Artificial, Big Data, Metodologias Ágeis.
- Voluntariado: Instrutor de programação para jovens em ONGs locais (2022-Atual).
- Hobbies: Leitura sobre inovação tecnológica, maratonas de hackathon, ciclismo.

In [9]:
content = result.document.export_to_markdown()
content

"## THOMAS A. ANDERSON\n\n- ✉ thomas.anderson@email.com\n- ▷ linkedin.com/in/thomasanderson\n- ▷ github.com/thomasanderson-dev\n\n## OBJETIVO\n\nProfissional de tecnologia com 5 anos de experiência em desenvolvimento de software e análise de dados, buscando ingressar no curso de Pós-Graduação em Ciência de Dados e Inteligência Artificial para ampliar conhecimentos em machine learning e big data. Comprometido em aplicar habilidades técnicas em projetos inovadores e contribuir para soluções orientadas por dados.\n\n## FORMAÇÃO ACADÊMICA\n\n## Bacharelado em Ciência da Computação\n\nUniversidade de São Paulo (USP) - São Paulo, SP Fev 2018 - Dez 2022\n\n- TCC: 'Otimização de Algoritmos de Machine Learning para Previsão de Demanda em Varejo'.\n- Participação em grupo de pesquisa em inteligência artificial.\n\n## EXPERIÊNCIA PROFISSIONAL\n\n## Engenheiro de Software Júnior | TechSolutions Brasil\n\nJan 2023 - Atual\n\n- Desenvolvimento de APIs em Python e Node.js para integração de sistemas de gestão empresarial.\n- Implementação de testes automatizados, reduzindo bugs em produção em 30%.\n- Colaboração em equipes ágeis (Scrum) para entrega de projetos em cloud (AWS).\n\n## Estagiário em Análise de Dados | InovaData Analytics\n\nMar 2021 - Dez 2022\n\n- Criação de dashboards em Power BI para monitoramento de KPIs de vendas.\n- Processamento de datasets com Pandas e SQL, identificando insights para redução de custos.\n- Automação de relatórios mensais, economizando 15 horas mensais da equipe.\n\n## Desenvolvedor Full-Stack Freelancer\n\n## Jun 2020 - Fev 2021\n\n- Construção de aplicações web com React e Django para clientes de e-commerce.\n- Integração de sistemas de pagamento (PagSeguro, Mercado Pago).\n\n## HABILIDADES TÉCNICAS\n\n- Linguagens: Python, Java, JavaScript, SQL\n\n- Frameworks: React, Node.js, Django\n\n- Banco de Dados: MySQL, MongoDB, PostgreSQL\n\n- Ferramentas: Git, Docker, Jupyter Notebook, Power BI\n\n- Cloud: AWS (EC2, S3), Google Cloud Platform\n\n- Análise de Dados: Pandas, NumPy, Tableau\n\n## CERTIFICAÇÕES\n\n- Certificado AWS Certified Developer - Associate (2023)\n- Scrum Master Certified (SMC) - CertiProf (2022)\n- Google Data Analytics Professional Certificate (2021)\n\n## IDIOMAS\n\n- ●\n\n- Português: Nativo\n\n- Inglês: Avançado (TOEFL: 92/120)\n\n- ●\n\n- Espanhol: Intermediário\n\n## PROJETOS RELEVANTES\n\n## Sistema de Recomendação para E-commerce\n\n- Desenvolvimento de modelo de ML em Python para personalizar sugestões de produtos, aumentando conversões em 18%.\n\n## Plataforma de Gestão de Projetos\n\n- Aplicação web full-stack (React + Django) para gestão de tarefas, utilizada por 500+ usuários.\n\n## INFORMAÇÕES ADICIONAIS\n\n- Interesses: Inteligência Artificial, Big Data, Metodologias Ágeis.\n- Voluntariado: Instrutor de programação para jovens em ONGs locais (2022-Atual).\n- Hobbies: Leitura sobre inovação tecnológica, maratonas de hackathon, ciclismo."

### Outra forma de carregar arquivos com Docling

In [10]:
source = 'https://arxiv.org/pdf/2408.09869'
converter = DocumentConverter()
result = converter.convert(source=source)
print(result.document.export_to_markdown())

[INFO] 2026-06-28 18:49:11,717 [RapidOCR] base.py:23: Using engine_name: onnxruntime
[INFO] 2026-06-28 18:49:11,724 [RapidOCR] download_file.py:60: File exists and is valid: /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_det_small.onnx
[INFO] 2026-06-28 18:49:11,724 [RapidOCR] main.py:63: Using /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_det_small.onnx
[INFO] 2026-06-28 18:49:11,749 [RapidOCR] base.py:23: Using engine_name: onnxruntime
[INFO] 2026-06-28 18:49:11,751 [RapidOCR] download_file.py:60: File exists and is valid: /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-06-28 18:49:11,751 [RapidOCR] main.py:63: Using /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-06-28 18:49:11,774 [RapidOCR] base.py:23: Using engine_name: onnxruntime
[INFO] 2026-06-28 18:49:11,787 [RapidOCR] download_file.py:60: File exists and is valid: /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_rec_small.onnx
[INFO] 2026-06-28 18:49:11,787 [RapidOCR] main.py:63: Using /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_rec_small.onnx

Loading weights:   0%|          | 0/770 [00:00<?, ?it/s]

<!-- image -->

## Docling Technical Report

## Version 1.0

Christoph Auer Maksym Lysak Ahmed Nassar Michele Dolfi Nikolaos Livathinos Panos Vagenas Cesar Berrospi Ramis Matteo Omenetti Fabian Lindlbauer Kasper Dinkla Lokesh Mishra Yusik Kim Shubham Gupta Rafael Teixeira de Lima Valery Weber Lucas Morin Ingmar Meijer Viktor Kuropiatnyk Peter W. J. Staar

AI4K Group, IBM Research R¨ uschlikon, Switzerland

## Abstract

This technical report introduces Docling , an easy to use, self-contained, MITlicensed open-source package for PDF document conversion. It is powered by state-of-the-art specialized AI models for layout analysis (DocLayNet) and table structure recognition (TableFormer), and runs efficiently on commodity hardware in a small resource budget. The code interface allows for easy extensibility and addition of new features and models.

## 1 Introduction

Converting PDF documents back into a machine-processable format has been a major challenge for decades due to their huge variability in formats, weak standardization and printing-optimized characteristic, which discards most structural features and metadata. With the advent of LLMs and popular application patterns such as retrieval-augmented generation (RAG), leveraging the rich content embedded in PDFs has become ever more relevant. In the past decade, several powerful document understanding solutions have emerged on the market, most of which are commercial software, cloud offerings [3] and most recently, multi-modal vision-language models. As of today, only a handful of open-source tools cover PDF conversion, leaving a significant feature and quality gap to proprietary solutions.

With Docling , we open-source a very capable and efficient document conversion tool which builds on the powerful, specialized AI models and datasets for layout analysis and table structure recognition we developed and presented in the recent past [12, 13, 9]. Docling is designed as a simple, self-contained python library with permissive license, running entirely locally on commodity hardware. Its code architecture allows for easy extensibility and addition of new features and models.

Here is what Docling delivers today:

- Converts PDF documents to JSON or Markdown format, stable and lightning fast
- Understands detailed page layout, reading order, locates figures and recovers table structures
- Extracts metadata from the document, such as title, authors, references and language
- Optionally applies OCR, e.g. for scanned PDFs
- Can be configured to be optimal for batch-mode (i.e high throughput, low time-to-solution)
- or interactive mode (compromise on efficiency, low time-to-solution)
- Can leverage different accelerators (GPU, MPS, etc).

## 2 Getting Started

To use Docling, you can simply install the docling package from PyPI. Documentation and examples are available in our GitHub repository at github.com/DS4SD/docling. All required model assets 1 are downloaded to a local huggingface datasets cache on first use, unless you choose to pre-install the model assets in advance.

Docling provides an easy code interface to convert PDF documents from file system, URLs or binary streams, and retrieve the output in either JSON or Markdown format. For convenience, separate methods are offered to convert single documents or batches of documents. A basic usage example is illustrated below. Further examples are available in the Doclign code repository.

from docling.document\_converter import DocumentConverter

```
source = "https://arxiv.org/pdf/2206.01062" # PDF path or URL converter = DocumentConverter() result = converter.convert_single(source) print(result.render_as_markdown()) # output: "## DocLayNet: A Large Human -Annotated Dataset for Document -Layout Analysis [...]"
```

Optionally, you can configure custom pipeline features and runtime options, such as turning on or off features (e.g. OCR, table structure recognition), enforcing limits on the input document size, and defining the budget of CPU threads. Advanced usage examples and options are documented in the README file. Docling also provides a Dockerfile to demonstrate how to install and run it inside a container.

## 3 Processing pipeline

Docling implements a linear pipeline of operations, which execute sequentially on each given document (see Fig. 1). Each document is first parsed by a PDF backend, which retrieves the programmatic text tokens, consisting of string content and its coordinates on the page, and also renders a bitmap image of each page to support downstream operations. Then, the standard model pipeline applies a sequence of AI models independently on every page in the document to extract features and content, such as layout and table structures. Finally, the results from all pages are aggregated and passed through a post-processing stage, which augments metadata, detects the document language, infers reading-order and eventually assembles a typed document object which can be serialized to JSON or Markdown.

## 3.1 PDF backends

Two basic requirements to process PDF documents in our pipeline are a) to retrieve all text content and their geometric coordinates on each page and b) to render the visual representation of each page as it would appear in a PDF viewer. Both these requirements are encapsulated in Docling's PDF backend interface. While there are several open-source PDF parsing libraries available for python, we faced major obstacles with all of them for different reasons, among which were restrictive licensing (e.g. pymupdf [7]), poor speed or unrecoverable quality issues, such as merged text cells across far-apart text tokens or table columns (pypdfium, PyPDF) [15, 14].

[1 see huggingface.co/ds4sd/docling-models/](https://huggingface.co/ds4sd/docling-models/)

Figure 1: Sketch of Docling's default processing pipeline. The inner part of the model pipeline is easily customizable and extensible.

<!-- image -->

We therefore decided to provide multiple backend choices, and additionally open-source a custombuilt PDF parser, which is based on the low-level qpdf [4] library. It is made available in a separate package named docling-parse and powers the default PDF backend in Docling. As an alternative, we provide a PDF backend relying on pypdfium , which may be a safe backup choice in certain cases, e.g. if issues are seen with particular font encodings.

## 3.2 AI models

As part of Docling, we initially release two highly capable AI models to the open-source community, which have been developed and published recently by our team. The first model is a layout analysis model, an accurate object-detector for page elements [13]. The second model is TableFormer [12, 9], a state-of-the-art table structure recognition model. We provide the pre-trained weights (hosted on huggingface) and a separate package for the inference code as docling-ibm-models . Both models are also powering the open-access deepsearch-experience, our cloud-native service for knowledge exploration tasks.

## Layout Analysis Model

Our layout analysis model is an object-detector which predicts the bounding-boxes and classes of various elements on the image of a given page. Its architecture is derived from RT-DETR [16] and re-trained on DocLayNet [13], our popular human-annotated dataset for document-layout analysis, among other proprietary datasets. For inference, our implementation relies on the onnxruntime [5].

The Docling pipeline feeds page images at 72 dpi resolution, which can be processed on a single CPU with sub-second latency. All predicted bounding-box proposals for document elements are post-processed to remove overlapping proposals based on confidence and size, and then intersected with the text tokens in the PDF to group them into meaningful and complete units such as paragraphs, section titles, list items, captions, figures or tables.

## Table Structure Recognition

The TableFormer model [12], first published in 2022 and since refined with a custom structure token language [9], is a vision-transformer model for table structure recovery. It can predict the logical row and column structure of a given table based on an input image, and determine which table cells belong to column headers, row headers or the table body. Compared to earlier approaches, TableFormer handles many characteristics of tables, such as partial or no borderlines, empty cells, rows or columns, cell spans and hierarchy both on column-heading or row-heading level, tables with inconsistent indentation or alignment and other complexities. For inference, our implementation relies on PyTorch [2].

The Docling pipeline feeds all table objects detected in the layout analysis to the TableFormer model, by providing an image-crop of the table and the included text cells. TableFormer structure predictions are matched back to the PDF cells in post-processing to avoid expensive re-transcription text in the table image. Typical tables require between 2 and 6 seconds to be processed on a standard CPU, strongly depending on the amount of included table cells.

## OCR

Docling provides optional support for OCR, for example to cover scanned PDFs or content in bitmaps images embedded on a page. In our initial release, we rely on EasyOCR [1], a popular thirdparty OCR library with support for many languages. Docling, by default, feeds a high-resolution page image (216 dpi) to the OCR engine, to allow capturing small print detail in decent quality. While EasyOCR delivers reasonable transcription quality, we observe that it runs fairly slow on CPU (upwards of 30 seconds per page).

We are actively seeking collaboration from the open-source community to extend Docling with additional OCR backends and speed improvements.

## 3.3 Assembly

In the final pipeline stage, Docling assembles all prediction results produced on each page into a well-defined datatype that encapsulates a converted document, as defined in the auxiliary package docling-core . The generated document object is passed through a post-processing model which leverages several algorithms to augment features, such as detection of the document language, correcting the reading order, matching figures with captions and labelling metadata such as title, authors and references. The final output can then be serialized to JSON or transformed into a Markdown representation at the users request.

## 3.4 Extensibility

Docling provides a straight-forward interface to extend its capabilities, namely the model pipeline. A model pipeline constitutes the central part in the processing, following initial document parsing and preceding output assembly, and can be fully customized by sub-classing from an abstract baseclass ( BaseModelPipeline ) or cloning the default model pipeline. This effectively allows to fully customize the chain of models, add or replace models, and introduce additional pipeline configuration parameters. To use a custom model pipeline, the custom pipeline class to instantiate can be provided as an argument to the main document conversion methods. We invite everyone in the community to propose additional or alternative models and improvements.

Implementations of model classes must satisfy the python Callable interface. The \_\_call\_\_ method must accept an iterator over page objects, and produce another iterator over the page objects which were augmented with the additional features predicted by the model, by extending the provided PagePredictions data model accordingly.

## 4 Performance

In this section, we establish some reference numbers for the processing speed of Docling and the resource budget it requires. All tests in this section are run with default options on our standard test set distributed with Docling, which consists of three papers from arXiv and two IBM Redbooks, with a total of 225 pages. Measurements were taken using both available PDF backends on two different hardware systems: one MacBook Pro M3 Max, and one bare-metal server running Ubuntu 20.04 LTS on an Intel Xeon E5-2690 CPU. For reproducibility, we fixed the thread budget (through setting OMP NUM THREADS environment variable ) once to 4 (Docling default) and once to 16 (equal to full core count on the test hardware). All results are shown in Table 1.

If you need to run Docling in very low-resource environments, please consider configuring the pypdfium backend. While it is faster and more memory efficient than the default docling-parse backend, it will come at the expense of worse quality results, especially in table structure recovery.

Establishing GPU acceleration support for the AI models is currently work-in-progress and largely untested, but may work implicitly when CUDA is available and discovered by the onnxruntime and torch runtimes backing the Docling pipeline. We will deliver updates on this topic at in a future version of this report.

Table 1: Runtime characteristics of Docling with the standard model pipeline and settings, on our test dataset of 225 pages, on two different systems. OCR is disabled. We show the time-to-solution (TTS), computed throughput in pages per second, and the peak memory used (resident set size) for both the Docling-native PDF backend and for the pypdfium backend, using 4 and 16 threads.

| CPU                     | Thread budget   | native backend   | native backend   | native backend   | pypdfium backend   | pypdfium backend   | pypdfium backend   |
|-------------------------|-----------------|------------------|------------------|------------------|--------------------|--------------------|--------------------|
|                         |                 | TTS              | Pages/s          | Mem              | TTS                | Pages/s            | Mem                |
| Apple M3 Max (16 cores) | 4 16            | 177 s 167 s      | 1.27 1.34        | 6.20 GB          | 103 s 92 s         | 2.18 2.45          | 2.56 GB            |
| Intel(R) Xeon E5-2690   | 4 16            | 375 s 244 s      | 0.60 0.92        | 6.16 GB          | 239 s 143 s        | 0.94 1.57          | 2.42 GB            |

## 5 Applications

Thanks to the high-quality, richly structured document conversion achieved by Docling, its output qualifies for numerous downstream applications. For example, Docling can provide a base for detailed enterprise document search, passage retrieval or classification use-cases, or support knowledge extraction pipelines, allowing specific treatment of different structures in the document, such as tables, figures, section structure or references. For popular generative AI application patterns, such as retrieval-augmented generation (RAG), we provide quackling , an open-source package which capitalizes on Docling's feature-rich document output to enable document-native optimized vector embedding and chunking. It plugs in seamlessly with LLM frameworks such as LlamaIndex [8]. Since Docling is fast, stable and cheap to run, it also makes for an excellent choice to build document-derived datasets. With its powerful table structure recognition, it provides significant benefit to automated knowledge-base construction [11, 10]. Docling is also integrated within the open IBM data prep kit [6], which implements scalable data transforms to build large-scale multi-modal training datasets.

## 6 Future work and contributions

Docling is designed to allow easy extension of the model library and pipelines. In the future, we plan to extend Docling with several more models, such as a figure-classifier model, an equationrecognition model, a code-recognition model and more. This will help improve the quality of conversion for specific types of content, as well as augment extracted document metadata with additional information. Further investment into testing and optimizing GPU acceleration as well as improving the Docling-native PDF backend are on our roadmap, too.

We encourage everyone to propose or implement additional features and models, and will gladly take your inputs and contributions under review . The codebase of Docling is open for use and contribution, under the MIT license agreement and in alignment with our contributing guidelines included in the Docling repository. If you use Docling in your projects, please consider citing this technical report.

## References

- [1] J. AI. Easyocr: Ready-to-use ocr with 80+ supported languages. https://github.com/ JaidedAI/EasyOCR , 2024. Version: 1.7.0.
- [2] J. Ansel, E. Yang, H. He, N. Gimelshein, A. Jain, M. Voznesensky, B. Bao, P. Bell, D. Berard, E. Burovski, G. Chauhan, A. Chourdia, W. Constable, A. Desmaison, Z. DeVito, E. Ellison, W. Feng, J. Gong, M. Gschwind, B. Hirsh, S. Huang, K. Kalambarkar, L. Kirsch, M. Lazos, M. Lezcano, Y. Liang, J. Liang, Y. Lu, C. Luk, B. Maher, Y. Pan, C. Puhrsch, M. Reso, M. Saroufim, M. Y. Siraichi, H. Suk, M. Suo, P. Tillet, E. Wang, X. Wang, W. Wen, S. Zhang, X. Zhao, K. Zhou, R. Zou, A. Mathews, G. Chanan, P. Wu, and S. Chintala. Pytorch 2: Faster

machine learning through dynamic python bytecode transformation and graph compilation. In Proceedings of the 29th ACM International Conference on Architectural Support for Programming Languages and Operating Systems, Volume 2 (ASPLOS '24) . ACM, 4 2024. doi: 10.1145/3620665.3640366. URL https://pytorch.org/assets/pytorch2-2.pdf .

- [3] C. Auer, M. Dolfi, A. Carvalho, C. B. Ramis, and P. W. Staar. Delivering document conversion as a cloud service with high throughput and responsiveness. In 2022 IEEE 15th International Conference on Cloud Computing (CLOUD) , pages 363-373. IEEE, 2022.
- [4] J. Berkenbilt. Qpdf: A content-preserving pdf document transformer, 2024. URL https: //github.com/qpdf/qpdf .
- [5] O. R. developers. Onnx runtime. https://onnxruntime.ai/ , 2024. Version: 1.18.1.
- [6] IBM. Data Prep Kit: a community project to democratize and accelerate unstructured data preparation for LLM app developers, 2024. URL https://github.com/IBM/ data-prep-kit .
- [7] [A. S. Inc. PyMuPDF, 2024. URL https://github.com/pymupdf/PyMuPDF .](https://github.com/pymupdf/PyMuPDF)
- [8] [J. Liu. LlamaIndex, 11 2022. URL https://github.com/jerryjliu/llama\_index .](https://github.com/jerryjliu/llama_index)
- [9] M. Lysak, A. Nassar, N. Livathinos, C. Auer, and P. Staar. Optimized Table Tokenization for Table Structure Recognition. In Document Analysis and Recognition - ICDAR 2023: 17th International Conference, San Jos´ e, CA, USA, August 21-26, 2023, Proceedings, Part II , pages 37-50, Berlin, Heidelberg, Aug. 2023. Springer-Verlag. ISBN 978-3-031-41678-1. doi: 10. 1007/978-3-031-41679-8 3. URL https://doi.org/10.1007/978-3-031-41679-8\_3 .
- [10] L. Mishra, S. Dhibi, Y. Kim, C. Berrospi Ramis, S. Gupta, M. Dolfi, and P. Staar. Statements: Universal information extraction from tables with large language models for ESG KPIs. In D. Stammbach, J. Ni, T. Schimanski, K. Dutia, A. Singh, J. Bingler, C. Christiaen, N. Kushwaha, V. Muccione, S. A. Vaghefi, and M. Leippold, editors, Proceedings of the 1st Workshop on Natural Language Processing Meets Climate Change (ClimateNLP 2024) , pages 193-214, Bangkok, Thailand, Aug. 2024. Association for Computational Linguistics. URL https://aclanthology.org/2024.climatenlp-1.15 .
- [11] L. Morin, V. Weber, G. I. Meijer, F. Yu, and P. W. J. Staar. Patcid: an open-access dataset of chemical structures in patent documents. Nature Communications , 15(1):6532, August 2024. ISSN 2041-1723. doi: 10.1038/s41467-024-50779-y. URL https://doi.org/10.1038/ s41467-024-50779-y .
- [12] A. Nassar, N. Livathinos, M. Lysak, and P. Staar. Tableformer: Table structure understanding with transformers. In Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition , pages 4614-4623, 2022.
- [13] B. Pfitzmann, C. Auer, M. Dolfi, A. S. Nassar, and P. Staar. Doclaynet: a large humanannotated dataset for document-layout segmentation. pages 3743-3751, 2022.

### Docling com LangChain

In [11]:
!pip install -q langchain-docling

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [12]:
from langchain_docling import DoclingLoader

loader = DoclingLoader(path)
docs = loader.load()

[INFO] 2026-06-28 18:49:28,175 [RapidOCR] base.py:23: Using engine_name: onnxruntime
[INFO] 2026-06-28 18:49:28,181 [RapidOCR] download_file.py:60: File exists and is valid: /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_det_small.onnx
[INFO] 2026-06-28 18:49:28,181 [RapidOCR] main.py:63: Using /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_det_small.onnx
[INFO] 2026-06-28 18:49:28,213 [RapidOCR] base.py:23: Using engine_name: onnxruntime
[INFO] 2026-06-28 18:49:28,214 [RapidOCR] download_file.py:60: File exists and is valid: /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-06-28 18:49:28,215 [RapidOCR] main.py:63: Using /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-06-28 18:49:28,240 [RapidOCR] base.py:23: Using engine_name: onnxruntime
[INFO] 2026-06-28 18:49:28,253 [RapidOCR] download_file.py:60: File exists and is valid: /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_rec_small.onnx
[INFO] 2026-06-28 18:49:28,253 [RapidOCR] main.py:63: Using /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_rec_small.onnx

Loading weights:   0%|          | 0/770 [00:00<?, ?it/s]

In [13]:
docs

[Document(metadata={'source': 'Currículo1.pdf', 'dl_meta': {'schema_name': 'docling_core.transforms.chunker.DocMeta', 'version': '1.0.0', 'doc_items': [{'self_ref': '#/texts/2', 'parent': {'$ref': '#/groups/0'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 1, 'bbox': {'l': 75.053981775, 't': 718.5292976889551, 'r': 238.597327399458, 'b': 708.8120560914487, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 27]}]}, {'self_ref': '#/texts/3', 'parent': {'$ref': '#/groups/0'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 1, 'bbox': {'l': 75.053981775, 't': 703.9830326889552, 'r': 244.43147239945802, 'b': 694.2657910914487, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 32]}]}, {'self_ref': '#/texts/4', 'parent': {'$ref': '#/groups/0'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 1, 'bbox': {'l': 75.053981775, 't': 689.4367684389551, 'r': 246.878947399458, 'b': 679.7195268414487, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 31]}]}], 'headings': ['THOMAS A. ANDERSON'], 'origin': {'mimetype': 'application/pdf', 'binary_hash': 12414447013796290601, 'filename': 'Currículo1.pdf'}}}, page_content='THOMAS A. ANDERSON\n- ✉ thomas.anderson@email.com\n- ▷ linkedin.com/in/thomasanderson\n- ▷ github.com/thomasanderson-dev'),
 Document(metadata={'source': 'Currículo1.pdf', 'dl_meta': {'schema_name': 'docling_core.transforms.chunker.DocMeta', 'version': '1.0.0', 'doc_items': [{'self_ref': '#/texts/6', 'parent': {'$ref': '#/body'}, 'children': [], 'content_layer': 'body', 'label': 'text', 'prov': [{'page_no': 1, 'bbox': {'l': 72.0, 't': 591.9669162499999, 'r': 512.54883006, 'b': 514.9398086766471, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 370]}]}], 'headings': ['OBJETIVO'], 'origin': {'mimetype': 'application/pdf', 'binary_hash': 12414447013796290601, 'filename': 'Currículo1.pdf'}}}, page_content='OBJETIVO\nProfissional de tecnologia com 5 anos de experiência em desenvolvimento de software e análise de dados, buscando ingressar no curso de Pós-Graduação em Ciência de Dados e Inteligência Artificial para ampliar conhecimentos em machine learning e big data. Comprometido em aplicar habilidades técnicas em projetos inovadores e contribuir para soluções orientadas por dados.'),
 Document(metadata={'source': 'Currículo1.pdf', 'dl_meta': {'schema_name': 'docling_core.transforms.chunker.DocMeta', 'version': '1.0.0', 'doc_items': [{'self_ref': '#/texts/9', 'parent': {'$ref': '#/body'}, 'children': [], 'content_layer': 'body', 'label': 'text', 'prov': [{'page_no': 1, 'bbox': {'l': 72.0, 't': 436.64065274999996, 'r': 338.45508006, 'b': 409.30168342664706, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 67]}]}, {'self_ref': '#/texts/10', 'parent': {'$ref': '#/groups/1'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 1, 'bbox': {'l': 90.0, 't': 403.57384996999997, 'r': 488.26172255999995, 'b': 376.1762899266471, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 89]}]}, {'self_ref': '#/texts/11', 'parent': {'$ref': '#/groups/1'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 1, 'bbox': {'l': 90.0, 't': 370.44848996999997, 'r': 432.75585756, 'b': 359.6135804266471, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 63]}]}], 'headings': ['Bacharelado em Ciência da Computação'], 'origin': {'mimetype': 'application/pdf', 'binary_hash': 12414447013796290601, 'filename': 'Currículo1.pdf'}}}, page_content="Bacharelado em Ciência da Computação\nUniversidade de São Paulo (USP) - São Paulo, SP Fev 2018 - Dez 2022\n- TCC: 'Otimização de Algoritmos de Machine Learning para Previsão de Demanda em Varejo'.\n- Participação em grupo de pesquisa em inteligência artificial."),
 Document(metadata={'source': 'Currículo1.pdf', 'dl_meta': {'schema_name': 'docling_core.transforms.chunker.DocMeta', 'version': '1.0.0', 'doc_items': [{'self_ref': '#/texts/14', 'parent': {'$ref': '#/body'}, 'children': [], 'content_layer': 'body', 'label': 'text', 'prov': [{'page_no': 1, 'bbox': {'l': 72.0, 't': 281.3144542499999, 'r': 163.71093789, 'b': 270.53813842664704, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 16]}]}, {'self_ref': '#/texts/15', 'parent': {'$ref': '#/groups/2'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 1, 'bbox': {'l': 90.0, 't': 264.81029996999996, 'r': 514.06641006, 'b': 237.41276842664706, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 96]}]}, {'self_ref': '#/texts/16', 'parent': {'$ref': '#/groups/2'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 1, 'bbox': {'l': 90.0, 't': 231.68493996999996, 'r': 510.08203505999995, 'b': 204.28728842664714, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 75]}]}, {'self_ref': '#/texts/17', 'parent': {'$ref': '#/groups/2'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 1, 'bbox': {'l': 90.0, 't': 198.55956996999998, 'r': 506.15039256, 'b': 171.16191842664716, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 79]}]}], 'headings': ['Engenheiro de Software Júnior | TechSolutions Brasil'], 'origin': {'mimetype': 'application/pdf', 'binary_hash': 12414447013796290601, 'filename': 'Currículo1.pdf'}}}, page_content='Engenheiro de Software Júnior | TechSolutions Brasil\nJan 2023 - Atual\n- Desenvolvimento de APIs em Python e Node.js para integração de sistemas de gestão empresarial.\n- Implementação de testes automatizados, reduzindo bugs em produção em 30%.\n- Colaboração em equipes ágeis (Scrum) para entrega de projetos em cloud (AWS).'),
 Document(metadata={'source': 'Currículo1.pdf', 'dl_meta': {'schema_name': 'docling_core.transforms.chunker.DocMeta', 'version': '1.0.0', 'doc_items': [{'self_ref': '#/texts/19', 'parent': {'$ref': '#/body'}, 'children': [], 'content_layer': 'body', 'label': 'text', 'prov': [{'page_no': 1, 'bbox': {'l': 72.0, 't': 148.81286425000008, 'r': 186.77343789, 'b': 138.0365484266472, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 19]}]}, {'self_ref': '#/texts/20', 'parent': {'$ref': '#/groups/3'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 1, 'bbox': {'l': 90.0, 't': 132.30871996999997, 'r': 520.2714825599999, 'b': 121.4738104266471, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 73]}]}, {'self_ref': '#/texts/21', 'parent': {'$ref': '#/groups/3'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 1, 'bbox': {'l': 90.0, 't': 115.74608996999996, 'r': 510.73828505999995, 'b': 88.34843842664714, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 92]}]}, {'self_ref': '#/texts/22', 'parent': {'$ref': '#/groups/3'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 2, 'bbox': {'l': 90.0, 't': 767.18749997, 'r': 489.0527325599999, 'b': 739.789848426647, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 75]}]}], 'headings': ['Estagiário em Análise de Dados | InovaData Analytics'], 'origin': {'mimetype': 'application/pdf', 'binary_hash': 12414447013796290601, 'filename': 'Currículo1.pdf'}}}, page_content='Estagiário em Análise de Dados | InovaData Analytics\nMar 2021 - Dez 2022\n- Criação de dashboards em Power BI para monitoramento de KPIs de vendas.\n- Processamento de datasets com Pandas e SQL, identificando insights para redução de custos.\n- Automação de relatórios mensais, economizando 15 horas mensais da equipe.'),
 Document(metadata={'source': 'Currículo1.pdf', 'dl_meta': {'schema_name': 'docling_core.transforms.chunker.DocMeta', 'version': '1.0.0', 'doc_items': [{'self_ref': '#/texts/25', 'parent': {'$ref': '#/groups/4'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 2, 'bbox': {'l': 90.0, 't': 700.93676797, 'r': 471.6503925599999, 'b': 673.5391164266471, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 78]}]}, {'self_ref': '#/texts/26', 'parent': {'$ref': '#/groups/4'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 2, 'bbox': {'l': 90.0, 't': 667.81127997, 'r': 471.58593755999993, 'b': 656.9763704266471, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 64]}]}], 'headings': ['Jun 2020 - Fev 2021'], 'origin': {'mimetype': 'application/pdf', 'binary_hash': 12414447013796290601, 'filename': 'Currículo1.pdf'}}}, page_content='Jun 2020 - Fev 2021\n- Construção de aplicações web com React e Django para clientes de e-commerce.\n- Integração de sistemas de pagamento (PagSeguro, Mercado Pago).'),
 Document(metadata={'source': 'Currículo1.pdf', 'dl_meta': {'schema_name': 'docling_core.transforms.chunker.DocMeta', 'version': '1.0.0', 'doc_items': [{'self_ref': '#/texts/28', 'parent': {'$ref': '#/groups/6'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 2, 'bbox': {'l': 90.0, 't': 595.29857997, 'r': 336.83203506, 'b': 584.4636704266471, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 43]}]}, {'self_ref': '#/texts/29', 'parent': {'$ref': '#/groups/7'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 2, 'bbox': {'l': 90.0, 't': 578.73583997, 'r': 303.23437506, 'b': 567.9009304266472, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 36]}]}, {'self_ref': '#/texts/30', 'parent': {'$ref': '#/groups/8'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 2, 'bbox': {'l': 90.0, 't': 562.17321997, 'r': 369.19335756, 'b': 551.3383104266471, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 44]}]}, {'self_ref': '#/texts/31', 'parent': {'$ref': '#/groups/9'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 2, 'bbox': {'l': 90.0, 't': 545.61046997, 'r': 395.87109756, 'b': 534.7755604266472, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 54]}]}, {'self_ref': '#/texts/32', 'parent': {'$ref': '#/groups/10'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 2, 'bbox': {'l': 90.0, 't': 529.04772997, 'r': 352.32422256, 'b': 518.2128204266471, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 45]}]}, {'self_ref': '#/texts/33', 'parent': {'$ref': '#/groups/11'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 2, 'bbox': {'l': 90.0, 't': 512.48510997, 'r': 341.88281256, 'b': 501.6502004266472, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 42]}]}], 'headings': ['HABILIDADES TÉCNICAS'], 'origin': {'mimetype': 'application/pdf', 'binary_hash': 12414447013796290601, 'filename': 'Currículo1.pdf'}}}, page_content='HABILIDADES TÉCNICAS\n- Linguagens: Python, Java, JavaScript, SQL\n- Frameworks: React, Node.js, Django\n- Banco de Dados: MySQL, MongoDB, PostgreSQL\n- Ferramentas: Git, Docker, Jupyter Notebook, Power BI\n- Cloud: AWS (EC2, S3), Google Cloud Platform\n- Análise de Dados: Pandas, NumPy, Tableau'),
 Document(metadata={'source': 'Currículo1.pdf', 'dl_meta': {'schema_name': 'docling_core.transforms.chunker.DocMeta', 'version': '1.0.0', 'doc_items': [{'self_ref': '#/texts/35', 'parent': {'$ref': '#/groups/12'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 2, 'bbox': {'l': 90.0, 't': 439.97240997, 'r': 407.03906256, 'b': 429.13750042664714, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 56]}]}, {'self_ref': '#/texts/36', 'parent': {'$ref': '#/groups/12'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 2, 'bbox': {'l': 90.0, 't': 423.40966997, 'r': 370.75195506, 'b': 412.5747604266471, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 49]}]}, {'self_ref': '#/texts/37', 'parent': {'$ref': '#/groups/12'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 2, 'bbox': {'l': 90.0, 't': 406.84691997, 'r': 394.85742006, 'b': 396.0120104266471, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 55]}]}], 'headings': ['CERTIFICAÇÕES'], 'origin': {'mimetype': 'application/pdf', 'binary_hash': 12414447013796290601, 'filename': 'Currículo1.pdf'}}}, page_content='CERTIFICAÇÕES\n- Certificado AWS Certified Developer - Associate (2023)\n- Scrum Master Certified (SMC) - CertiProf (2022)\n- Google Data Analytics Professional Certificate (2021)'),
 Document(metadata={'source': 'Currículo1.pdf', 'dl_meta': {'schema_name': 'docling_core.transforms.chunker.DocMeta', 'version': '1.0.0', 'doc_items': [{'self_ref': '#/texts/39', 'parent': {'$ref': '#/groups/14'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 2, 'bbox': {'l': 90.0, 't': 334.33410997, 'r': 100.582031235, 'b': 323.73348301364354, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 1]}]}, {'self_ref': '#/texts/40', 'parent': {'$ref': '#/groups/15'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 2, 'bbox': {'l': 108.0, 't': 334.27551625, 'r': 207.95507856, 'b': 323.4992004266471, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 17]}]}, {'self_ref': '#/texts/41', 'parent': {'$ref': '#/groups/16'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 2, 'bbox': {'l': 90.0, 't': 317.77147997, 'r': 294.06445506, 'b': 306.9365704266471, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 34]}]}, {'self_ref': '#/texts/42', 'parent': {'$ref': '#/groups/17'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 2, 'bbox': {'l': 90.0, 't': 301.20873997, 'r': 100.582031235, 'b': 290.60811301364356, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 1]}]}, {'self_ref': '#/texts/43', 'parent': {'$ref': '#/groups/18'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 2, 'bbox': {'l': 108.0, 't': 301.15014625000003, 'r': 237.99023256, 'b': 290.37383042664715, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 23]}]}], 'headings': ['IDIOMAS'], 'origin': {'mimetype': 'application/pdf', 'binary_hash': 12414447013796290601, 'filename': 'Currículo1.pdf'}}}, page_content='IDIOMAS\n- ●\n- Português: Nativo\n- Inglês: Avançado (TOEFL: 92/120)\n- ●\n- Espanhol: Intermediário'),
 Document(metadata={'source': 'Currículo1.pdf', 'dl_meta': {'schema_name': 'docling_core.transforms.chunker.DocMeta', 'version': '1.0.0', 'doc_items': [{'self_ref': '#/texts/46', 'parent': {'$ref': '#/groups/19'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 2, 'bbox': {'l': 90.0, 't': 212.13329996999994, 'r': 511.93945506, 'b': 184.735648426647, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 114]}]}], 'headings': ['Sistema de Recomendação para E-commerce'], 'origin': {'mimetype': 'application/pdf', 'binary_hash': 12414447013796290601, 'filename': 'Currículo1.pdf'}}}, page_content='Sistema de Recomendação para E-commerce\n- Desenvolvimento de modelo de ML em Python para personalizar sugestões de produtos, aumentando conversões em 18%.'),
 Document(metadata={'source': 'Currículo1.pdf', 'dl_meta': {'schema_name': 'docling_core.transforms.chunker.DocMeta', 'version': '1.0.0', 'doc_items': [{'self_ref': '#/texts/48', 'parent': {'$ref': '#/groups/20'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 2, 'bbox': {'l': 90.0, 't': 162.44530996999993, 'r': 506.1855450599999, 'b': 135.04753242664708, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 96]}]}], 'headings': ['Plataforma de Gestão de Projetos'], 'origin': {'mimetype': 'application/pdf', 'binary_hash': 12414447013796290601, 'filename': 'Currículo1.pdf'}}}, page_content='Plataforma de Gestão de Projetos\n- Aplicação web full-stack (React + Django) para gestão de tarefas, utilizada por 500+ usuários.'),
 Document(metadata={'source': 'Currículo1.pdf', 'dl_meta': {'schema_name': 'docling_core.transforms.chunker.DocMeta', 'version': '1.0.0', 'doc_items': [{'self_ref': '#/texts/50', 'parent': {'$ref': '#/groups/21'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 3, 'bbox': {'l': 90.0, 't': 739.78369097, 'r': 447.68554506, 'b': 728.9487814266471, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 68]}]}, {'self_ref': '#/texts/51', 'parent': {'$ref': '#/groups/21'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 3, 'bbox': {'l': 90.0, 't': 723.22094697, 'r': 474.93750005999993, 'b': 695.8234154266471, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 81]}]}, {'self_ref': '#/texts/52', 'parent': {'$ref': '#/groups/21'}, 'children': [], 'content_layer': 'body', 'label': 'list_item', 'prov': [{'page_no': 3, 'bbox': {'l': 90.0, 't': 690.09545897, 'r': 488.26758006, 'b': 662.6980474266471, 'coord_origin': 'BOTTOMLEFT'}, 'charspan': [0, 80]}]}], 'headings': ['INFORMAÇÕES ADICIONAIS'], 'origin': {'mimetype': 'application/pdf', 'binary_hash': 12414447013796290601, 'filename': 'Currículo1.pdf'}}}, page_content='INFORMAÇÕES ADICIONAIS\n- Interesses: Inteligência Artificial, Big Data, Metodologias Ágeis.\n- Voluntariado: Instrutor de programação para jovens em ONGs locais (2022-Atual).\n- Hobbies: Leitura sobre inovação tecnológica, maratonas de hackathon, ciclismo.')]

In [14]:
for d in docs[:3]:
    print(f"- {d.page_content=}")

- d.page_content='THOMAS A. ANDERSON\n- ✉ thomas.anderson@email.com\n- ▷ linkedin.com/in/thomasanderson\n- ▷ github.com/thomasanderson-dev'
- d.page_content='OBJETIVO\nProfissional de tecnologia com 5 anos de experiência em desenvolvimento de software e análise de dados, buscando ingressar no curso de Pós-Graduação em Ciência de Dados e Inteligência Artificial para ampliar conhecimentos em machine learning e big data. Comprometido em aplicar habilidades técnicas em projetos inovadores e contribuir para soluções orientadas por dados.'
- d.page_content="Bacharelado em Ciência da Computação\nUniversidade de São Paulo (USP) - São Paulo, SP Fev 2018 - Dez 2022\n- TCC: 'Otimização de Algoritmos de Machine Learning para Previsão de Demanda em Varejo'.\n- Participação em grupo de pesquisa em inteligência artificial."

## Carregando a LLM

In [15]:
from langchain_groq import ChatGroq

def load_llm(id_model, temperature):
    llm = ChatGroq(
        model=id_model,
        temperature=temperature,
        max_tokens=None,
        timeout=None,
        max_retries=2
    )
    return llm

In [16]:
id_model = "llama-3.3-70b-versatile"
temperature = 0.7

llm = load_llm(id_model, temperature)

## Testes iniciais

In [17]:
prompt = f"""
Resuma esse currículo em 1 parágrafo:
{content}
"""

In [18]:
prompt

"\nResuma esse currículo em 1 parágrafo:\n## THOMAS A. ANDERSON\n\n- ✉ thomas.anderson@email.com\n- ▷ linkedin.com/in/thomasanderson\n- ▷ github.com/thomasanderson-dev\n\n## OBJETIVO\n\nProfissional de tecnologia com 5 anos de experiência em desenvolvimento de software e análise de dados, buscando ingressar no curso de Pós-Graduação em Ciência de Dados e Inteligência Artificial para ampliar conhecimentos em machine learning e big data. Comprometido em aplicar habilidades técnicas em projetos inovadores e contribuir para soluções orientadas por dados.\n\n## FORMAÇÃO ACADÊMICA\n\n## Bacharelado em Ciência da Computação\n\nUniversidade de São Paulo (USP) - São Paulo, SP Fev 2018 - Dez 2022\n\n- TCC: 'Otimização de Algoritmos de Machine Learning para Previsão de Demanda em Varejo'.\n- Participação em grupo de pesquisa em inteligência artificial.\n\n## EXPERIÊNCIA PROFISSIONAL\n\n## Engenheiro de Software Júnior | TechSolutions Brasil\n\nJan 2023 - Atual\n\n- Desenvolvimento de APIs em Python e Node.js para integração de sistemas de gestão empresarial.\n- Implementação de testes automatizados, reduzindo bugs em produção em 30%.\n- Colaboração em equipes ágeis (Scrum) para entrega de projetos em cloud (AWS).\n\n## Estagiário em Análise de Dados | InovaData Analytics\n\nMar 2021 - Dez 2022\n\n- Criação de dashboards em Power BI para monitoramento de KPIs de vendas.\n- Processamento de datasets com Pandas e SQL, identificando insights para redução de custos.\n- Automação de relatórios mensais, economizando 15 horas mensais da equipe.\n\n## Desenvolvedor Full-Stack Freelancer\n\n## Jun 2020 - Fev 2021\n\n- Construção de aplicações web com React e Django para clientes de e-commerce.\n- Integração de sistemas de pagamento (PagSeguro, Mercado Pago).\n\n## HABILIDADES TÉCNICAS\n\n- Linguagens: Python, Java, JavaScript, SQL\n\n- Frameworks: React, Node.js, Django\n\n- Banco de Dados: MySQL, MongoDB, PostgreSQL\n\n- Ferramentas: Git, Docker, Jupyter Notebook, Power BI\n\n- Cloud: AWS (EC2, S3), Google Cloud Platform\n\n- Análise de Dados: Pandas, NumPy, Tableau\n\n## CERTIFICAÇÕES\n\n- Certificado AWS Certified Developer - Associate (2023)\n- Scrum Master Certified (SMC) - CertiProf (2022)\n- Google Data Analytics Professional Certificate (2021)\n\n## IDIOMAS\n\n- ●\n\n- Português: Nativo\n\n- Inglês: Avançado (TOEFL: 92/120)\n\n- ●\n\n- Espanhol: Intermediário\n\n## PROJETOS RELEVANTES\n\n## Sistema de Recomendação para E-commerce\n\n- Desenvolvimento de modelo de ML em Python para personalizar sugestões de produtos, aumentando conversões em 18%.\n\n## Plataforma de Gestão de Projetos\n\n- Aplicação web full-stack (React + Django) para gestão de tarefas, utilizada por 500+ usuários.\n\n## INFORMAÇÕES ADICIONAIS\n\n- Interesses: Inteligência Artificial, Big Data, Metodologias Ágeis.\n- Voluntariado: Instrutor de programação para jovens em ONGs locais (2022-Atual).\n- Hobbies: Leitura sobre inovação tecnológica, maratonas de hackathon, ciclismo.\n"

In [19]:
output = llm.invoke(prompt)
output.content

'Thomas A. Anderson é um profissional de tecnologia com 5 anos de experiência em desenvolvimento de software e análise de dados. Ele busca ingressar no curso de Pós-Graduação em Ciência de Dados e Inteligência Artificial para ampliar seus conhecimentos em machine learning e big data. Formado em Ciência da Computação pela Universidade de São Paulo (USP), Thomas tem experiência em desenvolvimento de APIs, testes automatizados e colaboração em equipes ágeis. Ele também tem habilidades em linguagens como Python, Java, JavaScript e SQL, além de frameworks como React, Node.js e Django. Thomas é certificado em AWS Certified Developer - Associate, Scrum Master Certified e Google Data Analytics Professional Certificate, e é fluente em português, inglês e intermediário em espanhol. Além disso, ele tem projetos relevantes em sua carreira, como o desenvolvimento de um sistema de recomendação para e-commerce e uma plataforma de gestão de projetos. Thomas é comprometido em aplicar suas habilidades técnicas em projetos inovadores e contribuir para soluções orientadas por dados.'

## Processamento e exibição do resultado

In [20]:
def format_res(res, return_thinking=False):
    res = res.strip()

    if return_thinking:
        res = res.replace("<think>", "[pensando...]")
        res = res.replace("</think>", "\n---\n")
    else:
        if "</think>" in res:
            res = res.split("</think>")[-1].strip()
    
    return res

def show_res(res):
    from IPython.display import Markdown

    display(Markdown(res))

In [21]:
res = format_res(output.content)

show_res(res)

Thomas A. Anderson é um profissional de tecnologia com 5 anos de experiência em desenvolvimento de software e análise de dados. Ele busca ingressar no curso de Pós-Graduação em Ciência de Dados e Inteligência Artificial para ampliar seus conhecimentos em machine learning e big data. Formado em Ciência da Computação pela Universidade de São Paulo (USP), Thomas tem experiência em desenvolvimento de APIs, testes automatizados e colaboração em equipes ágeis. Ele também tem habilidades em linguagens como Python, Java, JavaScript e SQL, além de frameworks como React, Node.js e Django. Thomas é certificado em AWS Certified Developer - Associate, Scrum Master Certified e Google Data Analytics Professional Certificate, e é fluente em português, inglês e intermediário em espanhol. Além disso, ele tem projetos relevantes em sua carreira, como o desenvolvimento de um sistema de recomendação para e-commerce e uma plataforma de gestão de projetos. Thomas é comprometido em aplicar suas habilidades técnicas em projetos inovadores e contribuir para soluções orientadas por dados.

## Construindo o prompt

### Base do prompt

In [22]:
from langchain_core.prompts import ChatPromptTemplate, HumanMessagePromptTemplate, MessagesPlaceholder

In [23]:
prompt_template = ChatPromptTemplate.from_template("""
Você é um especialista em Recursos Humanos com vasta experiência em análise de currículos. Sua tarefa é analisar o conteúdo a seguir e extrair os dados conforme 
o formato abaixo, para cada um dos campos.
Responda apenas com o JSON estruturado e utilize somente essas chaves. Cuide para que os nomes das chaves sejam exatamente esses. 
Não adicione explicações ou anotações fora do JSON.
Schema desejado:
{schema}

---

Currículo a ser analisado:
'{cv}'
""")

In [24]:
prompt_template

ChatPromptTemplate(input_variables=['cv', 'schema'], input_types={}, partial_variables={}, messages=[HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['cv', 'schema'], input_types={}, partial_variables={}, template="\nVocê é um especialista em Recursos Humanos com vasta experiência em análise de currículos. Sua tarefa é analisar o conteúdo a seguir e extrair os dados conforme \no formato abaixo, para cada um dos campos.\nResponda apenas com o JSON estruturado e utilize somente essas chaves. Cuide para que os nomes das chaves sejam exatamente esses. \nNão adicione explicações ou anotações fora do JSON.\nSchema desejado:\n{schema}\n\n---\n\nCurrículo a ser analisado:\n'{cv}'\n"), additional_kwargs={})])

### Definindo o Schema para análise de currículos

A seguir está o schema com os campos que queremos extrair de cada currículo analisado, baseado em campos:

- Nome completo
- Área de atuação
- Resumo do perfil
- Principais competências
- Educação
- Sugestão de pergunta para entrevista

In [25]:
schema = """
{
    "name": "Nome completo do candidato",
    "area": "Área ou setor principal onde o candidato atua",
    "summary": "Resumo objetivo sobre o perfil profissional do candidato",
    "skills": ["competência 1", "competência 2", "..."],
    "education": "Resumo da formação acadêmica mais relevante",
    "interview_questions": "Pergunta útil para entrevista com base no currículo, para esclarecer algum ponto ou explorar melhor"
}
"""

In [26]:
chain = prompt_template | llm
output = chain.invoke({"schema": schema, "cv": content})

show_res(output.content)

```json
{
    "name": "Thomas A. Anderson",
    "area": "Tecnologia da Informação e Análise de Dados",
    "summary": "Profissional de tecnologia com 5 anos de experiência em desenvolvimento de software e análise de dados, com habilidades em machine learning, big data e comprometimento com soluções orientadas por dados",
    "skills": [
        "Desenvolvimento de software",
        "Análise de dados",
        "Machine learning",
        "Big data",
        "Linguagens de programação (Python, Java, JavaScript, SQL)",
        "Frameworks (React, Node.js, Django)",
        "Banco de dados (MySQL, MongoDB, PostgreSQL)",
        "Ferramentas (Git, Docker, Jupyter Notebook, Power BI)",
        "Cloud (AWS, Google Cloud Platform)"
    ],
    "education": "Bacharelado em Ciência da Computação pela Universidade de São Paulo (USP), com TCC em 'Otimização de Algoritmos de Machine Learning para Previsão de Demanda em Varejo' e participação em grupo de pesquisa em inteligência artificial",
    "interview_questions": "Como você acredita que sua experiência em desenvolvimento de software e análise de dados possa contribuir para o curso de Pós-Graduação em Ciência de Dados e Inteligência Artificial, e quais são seus objetivos de carreira após a conclusão do curso?"
}
```

### Reunindo em uma função

In [27]:
def process_cv(schema, content):
    chain = prompt_template | llm
    output = chain.invoke({"schema": schema, "cv": content})

    res = format_res(output.content)

    return output, res

In [28]:
output, res = process_cv(schema, content)

In [29]:
output

AIMessage(content='```json\n{\n    "name": "Thomas A. Anderson",\n    "area": "Tecnologia da Informação",\n    "summary": "Profissional de tecnologia com 5 anos de experiência em desenvolvimento de software e análise de dados, com habilidades em machine learning e big data.",\n    "skills": [\n        "Python",\n        "Java",\n        "JavaScript",\n        "SQL",\n        "React",\n        "Node.js",\n        "Django",\n        "MySQL",\n        "MongoDB",\n        "PostgreSQL",\n        "Git",\n        "Docker",\n        "Jupyter Notebook",\n        "Power BI",\n        "AWS",\n        "Google Cloud Platform",\n        "Pandas",\n        "NumPy",\n        "Tableau"\n    ],\n    "education": "Bacharelado em Ciência da Computação pela Universidade de São Paulo (USP), com TCC em \'Otimização de Algoritmos de Machine Learning para Previsão de Demanda em Varejo\'.",\n    "interview_questions": "Como você aplicaria suas habilidades em machine learning e big data em um projeto real de análise de dados?"\n}\n```', additional_kwargs={}, response_metadata={'token_usage': {'completion_tokens': 246, 'prompt_tokens': 1106, 'total_tokens': 1352, 'completion_time': 0.540856031, 'completion_tokens_details': None, 'prompt_time': 0.062465974, 'prompt_tokens_details': None, 'queue_time': 0.24162957, 'total_time': 0.603322005}, 'model_name': 'llama-3.3-70b-versatile', 'system_fingerprint': 'fp_ce7bc1685b', 'service_tier': 'on_demand', 'finish_reason': 'stop', 'logprobs': None, 'model_provider': 'groq'}, id='lc_run--019f1035-9078-7e72-9fa4-b52f37aa2d45-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 1106, 'output_tokens': 246, 'total_tokens': 1352})

In [30]:
res

'```json\n{\n    "name": "Thomas A. Anderson",\n    "area": "Tecnologia da Informação",\n    "summary": "Profissional de tecnologia com 5 anos de experiência em desenvolvimento de software e análise de dados, com habilidades em machine learning e big data.",\n    "skills": [\n        "Python",\n        "Java",\n        "JavaScript",\n        "SQL",\n        "React",\n        "Node.js",\n        "Django",\n        "MySQL",\n        "MongoDB",\n        "PostgreSQL",\n        "Git",\n        "Docker",\n        "Jupyter Notebook",\n        "Power BI",\n        "AWS",\n        "Google Cloud Platform",\n        "Pandas",\n        "NumPy",\n        "Tableau"\n    ],\n    "education": "Bacharelado em Ciência da Computação pela Universidade de São Paulo (USP), com TCC em \'Otimização de Algoritmos de Machine Learning para Previsão de Demanda em Varejo\'.",\n    "interview_questions": "Como você aplicaria suas habilidades em machine learning e big data em um projeto real de análise de dados?"\n}\n```'

## Validando a saída

In [31]:
import json

def parse_res_llm(response_text: str, required_fields: list) -> dict:
    try:
        if "</think>" in response_text:
            response_text = response_text.split("</think>")[-1].strip()
        start_idx = response_text.find("{")
        end_idx = response_text.find("}") + 1
        if start_idx == -1 or end_idx == 0:
            raise json.JSONDecodeError("Nenhum JSON encontrado na resposta", doc=response_text, pos=0)
        
        json_str = response_text[start_idx:end_idx]
        info_cv = json.loads(json_str)

        for field in required_fields:
            if field not in info_cv:
                info_cv[field] = []

        return info_cv
    except json.JSONDecodeError:
        return

In [32]:
fields = [
    "name",
    "area",
    "summary",
    "skills",
    "education",
    "interview_questions"
]

In [33]:
structured_data = parse_res_llm(res, fields)
structured_data

{'name': 'Thomas A. Anderson',
 'area': 'Tecnologia da Informação',
 'summary': 'Profissional de tecnologia com 5 anos de experiência em desenvolvimento de software e análise de dados, com habilidades em machine learning e big data.',
 'skills': ['Python',
  'Java',
  'JavaScript',
  'SQL',
  'React',
  'Node.js',
  'Django',
  'MySQL',
  'MongoDB',
  'PostgreSQL',
  'Git',
  'Docker',
  'Jupyter Notebook',
  'Power BI',
  'AWS',
  'Google Cloud Platform',
  'Pandas',
  'NumPy',
  'Tableau'],
 'education': "Bacharelado em Ciência da Computação pela Universidade de São Paulo (USP), com TCC em 'Otimização de Algoritmos de Machine Learning para Previsão de Demanda em Varejo'.",
 'interview_questions': 'Como você aplicaria suas habilidades em machine learning e big data em um projeto real de análise de dados?'}

### Salvando e lendo os dados estruturados

In [34]:
path_json = "curriculos.json"

def save_json_csv(result, path_json):
    with open(path_json, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2, ensure_ascii=False)

save_json_csv(structured_data, path_json)

## Carregando o conteúdo do arquivo JSON

In [35]:
def load_json_cv(path_json):
    with open(path_json, "r", encoding='utf-8') as f:
        return json.load(f)
    
result_cv = load_json_cv(path_json)

In [36]:
for chave in result_cv.keys():
    print(chave)

name
area
summary
skills
education
interview_questions

## Exibição dos resultados

In [37]:
from IPython.display import display, Markdown

def show_cv_result(result: dict):
    md = f"### Análise e Resumo do Currículo\n"
    if "name" in result:
        md += f"- **Nome:** {result['name']}\n"
    if "area" in result:
        md += f"- **Área:** {result['area']}\n"
    if "skills" in result:
        md += f"- **Competências:** {','.join(result['skills'])}\n"
    if "summary" in result:
        md += f"- **Resumo do perfil:** {result['summary']}\n"
    if "interview_questions" in result:
        md += f"- **Pergunta sugerida:** {result['interview_questions']}\n"

    display(Markdown(md))

In [38]:
show_cv_result(result_cv)

### Análise e Resumo do Currículo
- **Nome:** Thomas A. Anderson
- **Área:** Tecnologia da Informação
- **Competências:** Python,Java,JavaScript,SQL,React,Node.js,Django,MySQL,MongoDB,PostgreSQL,Git,Docker,Jupyter Notebook,Power BI,AWS,Google Cloud Platform,Pandas,NumPy,Tableau
- **Resumo do perfil:** Profissional de tecnologia com 5 anos de experiência em desenvolvimento de software e análise de dados, com habilidades em machine learning e big data.
- **Pergunta sugerida:** Como você aplicaria suas habilidades em machine learning e big data em um projeto real de análise de dados?

## Criando vaga e descrição

In [39]:
job = {}

job['title'] = "Desenvolvedor(a) Full Stack"
job['description'] = "Estamos em busca de um(a) Desenvolvedor(a) Full Stack para integrar o time de tecnologia da nossa empresa, atuando em projetos estratégicos com foco em soluções escaláveis e orientadas a dados. O(a) profissional será responsável por desenvolver, manter e evoluir aplicações web robustas, além de colaborar com times multidisciplinares para entregar valor contínuo ao negócio."
job['details'] = """
Atividades:
- Desenvolver e manter aplicações web em ambientes modernos, utilizando tecnologias back-end e front-end.
- Trabalhar com equipes de produto, UX e dados para entender demandas e propor soluções.
- Criar APIs, integrações e dashboards interativos.
- Garantir boas práticas de versionamento, testes e documentação.
- Participar de revisões de código, deploys e melhorias contínuas na arquitetura das aplicações.

Pré-requisitos:
- Sólidos conhecimentos em Python, JavaScript e SQL.
- Experiência prática com frameworks como React, Node.js e Django.
- Familiaridade com versionamento de código usando Git.
- Experiência com serviços de nuvem, como AWS e Google Cloud Platform.
- Capacidade de trabalhar em equipe, com boa comunicação e perfil colaborativo.

Diferenciais:
- Conhecimento em Power BI ou outras ferramentas de visualização de dados.
- Experiência anterior em ambientes ágeis (Scrum, Kanban).
- Projetos próprios, contribuições open source ou portfólio técnico disponível.
- Certificações em nuvem ou áreas relacionadas à engenharia de software.
"""

## Salvando dados em um CSV

In [40]:
import csv
import os
import pandas as pd
import json

path_job_csv = "vagas.csv"

def safe_job_to_csv(data, filename):
    print("SALVANDO CSV")
    headers = ['title', 'description', 'details']
    file_exists = os.path.exists(filename)

    with open(filename, 'a', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=headers, delimiter=';')
        if not file_exists:
            writer.writeheader()
        writer.writerow(data)

In [41]:
safe_job_to_csv(job, path_job_csv)

SALVANDO CSV

In [42]:
df = pd.read_csv(path_job_csv, sep=';')
display(df)

,title,description,details
0,Desenvolvedor(a) Full Stack,Estamos em busca de um(a) Desenvolvedor(a) Ful...,\nAtividades:\n- Desenvolver e manter aplicaçõ...
1,Desenvolvedor(a) Full Stack,Estamos em busca de um(a) Desenvolvedor(a) Ful...,\nAtividades:\n- Desenvolver e manter aplicaçõ...

In [43]:
def load_job(csv_path):
    try:
        df = pd.read_csv(csv_path, sep = ';', encoding='utf-8')
        job = df.iloc[-1]
        prompt_text = f"""
            **Vaga para {job['title']}**

            **Descrição da Vaga:**
            {job['description']}

            **Detalhes completos:**
            {job['details']}
        """

        return prompt_text.strip()
    except FileNotFoundError:
        return "Erro: arquivo de vagas não encontrado"

In [44]:
job_details = load_job(path_job_csv)
print(job_details)

**Vaga para Desenvolvedor(a) Full Stack**

            **Descrição da Vaga:**
            Estamos em busca de um(a) Desenvolvedor(a) Full Stack para integrar o time de tecnologia da nossa empresa, atuando em projetos estratégicos com foco em soluções escaláveis e orientadas a dados. O(a) profissional será responsável por desenvolver, manter e evoluir aplicações web robustas, além de colaborar com times multidisciplinares para entregar valor contínuo ao negócio.

            **Detalhes completos:**

Atividades:
- Desenvolver e manter aplicações web em ambientes modernos, utilizando tecnologias back-end e front-end.
- Trabalhar com equipes de produto, UX e dados para entender demandas e propor soluções.
- Criar APIs, integrações e dashboards interativos.
- Garantir boas práticas de versionamento, testes e documentação.
- Participar de revisões de código, deploys e melhorias contínuas na arquitetura das aplicações.

Pré-requisitos:
- Sólidos conhecimentos em Python, JavaScript e SQL.
- Experiência prática com frameworks como React, Node.js e Django.
- Familiaridade com versionamento de código usando Git.
- Experiência com serviços de nuvem, como AWS e Google Cloud Platform.
- Capacidade de trabalhar em equipe, com boa comunicação e perfil colaborativo.

Diferenciais:
- Conhecimento em Power BI ou outras ferramentas de visualização de dados.
- Experiência anterior em ambientes ágeis (Scrum, Kanban).
- Projetos próprios, contribuições open source ou portfólio técnico disponível.
- Certificações em nuvem ou áreas relacionadas à engenharia de software.

## Modificando o prompt e a chain

In [49]:
prompt_template = ChatPromptTemplate.from_template("""
Você é um especialista em Recursos Humanos com vasta experiência em análise de currículos. 
Sua tarefa é analisar o conteúdo a seguir e extrair os dados conforme o formato abaixo, para cada um dos campos.
Importante: Responda apenas com o JSON estruturado e utilize somente essas chaves. Cuide para que os nomes das chaves sejam exatamente esses. 
Não adicione explicações ou anotações fora do JSON.
Schema desejado:
{schema}

---

Currículo a ser analisado:
'{cv}'

---

Vaga que o candidato está se candidatando:
'{job}'

""")
prompt_template

ChatPromptTemplate(input_variables=['cv', 'job', 'schema'], input_types={}, partial_variables={}, messages=[HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['cv', 'job', 'schema'], input_types={}, partial_variables={}, template="\nVocê é um especialista em Recursos Humanos com vasta experiência em análise de currículos. \nSua tarefa é analisar o conteúdo a seguir e extrair os dados conforme o formato abaixo, para cada um dos campos.\nImportante: Responda apenas com o JSON estruturado e utilize somente essas chaves. Cuide para que os nomes das chaves sejam exatamente esses. \nNão adicione explicações ou anotações fora do JSON.\nSchema desejado:\n{schema}\n\n---\n\nCurrículo a ser analisado:\n'{cv}'\n\n---\n\nVaga que o candidato está se candidatando:\n'{job}'\n\n"), additional_kwargs={})])

In [46]:
def process_cv(schema, content, job_details, prompt_template, llm):
    chain = prompt_template | llm
    output = chain.invoke({"schema": schema, "cv": content, "job": job_details})

    res = format_res(output.content)

    return output, res

In [50]:
output, res = process_cv(schema, content, job_details, prompt_template, llm)

In [51]:
output

AIMessage(content='```\n{\n    "name": "THOMAS A. ANDERSON",\n    "area": "Desenvolvimento de Software e Análise de Dados",\n    "summary": "Profissional de tecnologia com 5 anos de experiência em desenvolvimento de software e análise de dados, buscando ingressar no curso de Pós-Graduação em Ciência de Dados e Inteligência Artificial",\n    "skills": ["Python", "Java", "JavaScript", "SQL", "React", "Node.js", "Django", "MySQL", "MongoDB", "PostgreSQL", "Git", "Docker", "Jupyter Notebook", "Power BI", "AWS", "Google Cloud Platform", "Pandas", "NumPy", "Tableau"],\n    "education": "Bacharelado em Ciência da Computação pela Universidade de São Paulo (USP)",\n    "interview_questions": "Como você aplica habilidades técnicas em projetos inovadores e contribui para soluções orientadas por dados em sua experiência profissional?"\n}\n```', additional_kwargs={}, response_metadata={'token_usage': {'completion_tokens': 228, 'prompt_tokens': 1531, 'total_tokens': 1759, 'completion_time': 0.444770601, 'completion_tokens_details': None, 'prompt_time': 0.152298739, 'prompt_tokens_details': None, 'queue_time': 0.243399832, 'total_time': 0.59706934}, 'model_name': 'llama-3.3-70b-versatile', 'system_fingerprint': 'fp_f8b414701e', 'service_tier': 'on_demand', 'finish_reason': 'stop', 'logprobs': None, 'model_provider': 'groq'}, id='lc_run--019f103c-5abd-7143-8253-210ba3ebd76a-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 1531, 'output_tokens': 228, 'total_tokens': 1759})

In [52]:
res

'```\n{\n    "name": "THOMAS A. ANDERSON",\n    "area": "Desenvolvimento de Software e Análise de Dados",\n    "summary": "Profissional de tecnologia com 5 anos de experiência em desenvolvimento de software e análise de dados, buscando ingressar no curso de Pós-Graduação em Ciência de Dados e Inteligência Artificial",\n    "skills": ["Python", "Java", "JavaScript", "SQL", "React", "Node.js", "Django", "MySQL", "MongoDB", "PostgreSQL", "Git", "Docker", "Jupyter Notebook", "Power BI", "AWS", "Google Cloud Platform", "Pandas", "NumPy", "Tableau"],\n    "education": "Bacharelado em Ciência da Computação pela Universidade de São Paulo (USP)",\n    "interview_questions": "Como você aplica habilidades técnicas em projetos inovadores e contribui para soluções orientadas por dados em sua experiência profissional?"\n}\n```'

In [53]:
structured_data = parse_res_llm(res, fields)
save_json_csv(structured_data, path_json)
result_cv = load_json_cv("curriculos.json")
show_cv_result(result_cv)

### Análise e Resumo do Currículo
- **Nome:** THOMAS A. ANDERSON
- **Área:** Desenvolvimento de Software e Análise de Dados
- **Competências:** Python,Java,JavaScript,SQL,React,Node.js,Django,MySQL,MongoDB,PostgreSQL,Git,Docker,Jupyter Notebook,Power BI,AWS,Google Cloud Platform,Pandas,NumPy,Tableau
- **Resumo do perfil:** Profissional de tecnologia com 5 anos de experiência em desenvolvimento de software e análise de dados, buscando ingressar no curso de Pós-Graduação em Ciência de Dados e Inteligência Artificial
- **Pergunta sugerida:** Como você aplica habilidades técnicas em projetos inovadores e contribui para soluções orientadas por dados em sua experiência profissional?

## Análise detalhada

In [55]:
schema = """
{
  "name": "Nome completo do candidato",
  "area": "Área ou setor principal onde o candidato atua. Classifique em apenas uma: Desenvolvimento, Marketing, Vendas, Financeiro, Administrativo, Outros",
  "summary": "Resumo objetivo sobre o perfil profissional do candidato",
  "skills": ["competência 1", "competência 2", "..."],
  "education": "Resumo da formação acadêmica mais relevante",
  "interview_questions": ["Pelo menos 3 perguntas úteis para entrevista com base no currículo, para esclarecer algum ponto ou explorar melhor"],
  "strengths": ["Pontos fortes e aspectos que indicam alinhamento com o perfil ou vaga desejada"],
  "areas_for_development": ["Pontos que indicam possíveis lacunas, fragilidades ou necessidades de desenvolvimento"],
  "important_considerations": ["Observações específicas que merecem verificação ou cuidado adicional"],
  "final_recommendations": "Resumo avaliativo final com sugestões de próximos passos (ex: seguir com entrevista, indicar para outra vaga)"
}
"""

In [56]:
fields = [
    "name",
    "area",
    "summary",
    "skills",
    "education",
    "interview_questions",
    "strengths",
    "areas_for_development",
    "important_considerations",
    "final_recommendations"
]

In [57]:
output, res = process_cv(schema, content, job_details, prompt_template, llm)

In [60]:
res

'```json\n{\n  "name": "Thomas A. Anderson",\n  "area": "Desenvolvimento",\n  "summary": "Profissional de tecnologia com 5 anos de experiência em desenvolvimento de software e análise de dados, buscando ingressar no curso de Pós-Graduação em Ciência de Dados e Inteligência Artificial",\n  "skills": [\n    "Python",\n    "Java",\n    "JavaScript",\n    "SQL",\n    "React",\n    "Node.js",\n    "Django",\n    "MySQL",\n    "MongoDB",\n    "PostgreSQL",\n    "Git",\n    "Docker",\n    "Jupyter Notebook",\n    "Power BI",\n    "AWS",\n    "Google Cloud Platform"\n  ],\n  "education": "Bacharelado em Ciência da Computação pela Universidade de São Paulo (USP)",\n  "interview_questions": [\n    "Como você aplicaria suas habilidades em machine learning e big data em projetos de desenvolvimento de software?",\n    "Descreva sua experiência com equipes ágeis e como você contribuiu para a entrega de projetos em cloud",\n    "Como você lidou com desafios técnicos em seus projetos anteriores e quais foram as soluções implementadas?"\n  ],\n  "strengths": [\n    "Experiência em desenvolvimento de software e análise de dados",\n    "Conhecimento em linguagens de programação e frameworks relevantes",\n    "Familiaridade com serviços de nuvem e ferramentas de visualização de dados",\n    "Certificações em nuvem e áreas relacionadas à engenharia de software"\n  ],\n  "areas_for_development": [\n    "Necessidade de aprofundar conhecimentos em Ciência de Dados e Inteligência Artificial",\n    "Possível necessidade de melhorar habilidades de comunicação e trabalho em equipe"\n  ],\n  "important_considerations": [\n    "Verificar a compatibilidade das habilidades e experiência do candidato com as necessidades específicas da vaga",\n    "Avaliar a capacidade do candidato de trabalhar em equipe e colaborar com outros profissionais"\n  ],\n  "final_recommendations": "Recomendo seguir com a entrevista para avaliar melhor as habilidades e experiência do candidato, além de discutir como ele pode contribuir para a equipe de desenvolvimento da empresa"\n}\n```'

In [59]:
structured_data = parse_res_llm(res, fields)
save_json_csv(structured_data, path_json)
result_cv = load_json_cv("curriculos.json")

structured_data

{'name': 'Thomas A. Anderson',
 'area': 'Desenvolvimento',
 'summary': 'Profissional de tecnologia com 5 anos de experiência em desenvolvimento de software e análise de dados, buscando ingressar no curso de Pós-Graduação em Ciência de Dados e Inteligência Artificial',
 'skills': ['Python',
  'Java',
  'JavaScript',
  'SQL',
  'React',
  'Node.js',
  'Django',
  'MySQL',
  'MongoDB',
  'PostgreSQL',
  'Git',
  'Docker',
  'Jupyter Notebook',
  'Power BI',
  'AWS',
  'Google Cloud Platform'],
 'education': 'Bacharelado em Ciência da Computação pela Universidade de São Paulo (USP)',
 'interview_questions': ['Como você aplicaria suas habilidades em machine learning e big data em projetos de desenvolvimento de software?',
  'Descreva sua experiência com equipes ágeis e como você contribuiu para a entrega de projetos em cloud',
  'Como você lidou com desafios técnicos em seus projetos anteriores e quais foram as soluções implementadas?'],
 'strengths': ['Experiência em desenvolvimento de software e análise de dados',
  'Conhecimento em linguagens de programação e frameworks relevantes',
  'Familiaridade com serviços de nuvem e ferramentas de visualização de dados',
  'Certificações em nuvem e áreas relacionadas à engenharia de software'],
 'areas_for_development': ['Necessidade de aprofundar conhecimentos em Ciência de Dados e Inteligência Artificial',
  'Possível necessidade de melhorar habilidades de comunicação e trabalho em equipe'],
 'important_considerations': ['Verificar a compatibilidade das habilidades e experiência do candidato com as necessidades específicas da vaga',
  'Avaliar a capacidade do candidato de trabalhar em equipe e colaborar com outros profissionais'],
 'final_recommendations': 'Recomendo seguir com a entrevista para avaliar melhor as habilidades e experiência do candidato, além de discutir como ele pode contribuir para a equipe de desenvolvimento da empresa'}

In [61]:
from IPython.display import display, Markdown

def show_cv_result(result: dict):
    md = f"### 📄 Análise e Resumo do Currículo\n"
    if "name" in result:
        md += f"- **Nome:** {result['name']}\n"
    if "area" in result:
        md += f"- **Área de Atuação:** {result['area']}\n"
    if "skills" in result:
        md += f"- **Competências:** {', '.join(result['skills'])}\n"
    if "summary" in result:
        md += f"- **Resumo do Perfil:** {result['summary']}\n"
    if "interview_questions" in result:
        md += f"- **Perguntas sugeridas:**\n"
        md += "\n".join([f"  - {q}" for q in result["interview_questions"]]) + "\n"
    if "strengths" in result:
        md += f"- **Pontos fortes (ou Alinhamentos):**\n"
        md += "\n".join([f"  - {s}" for s in result["strengths"]]) + "\n"
    if "areas_for_development" in result:
        md += f"- **Pontos a desenvolver (ou Desalinhamentos):**\n"
        md += "\n".join([f"  - {a}" for a in result["areas_for_development"]]) + "\n"
    if "important_considerations" in result:
        md += f"- **Pontos de atenção:**\n"
        md += "\n".join([f"  - {i}" for i in result["important_considerations"]]) + "\n"
    if "final_recommendations" in result:
        md += f"- **Conclusão e recomendações:** {result['final_recommendations']}\n"
    display(Markdown(md))

show_cv_result(result_cv)

### 📄 Análise e Resumo do Currículo
- **Nome:** Thomas A. Anderson
- **Área de Atuação:** Desenvolvimento
- **Competências:** Python, Java, JavaScript, SQL, React, Node.js, Django, MySQL, MongoDB, PostgreSQL, Git, Docker, Jupyter Notebook, Power BI, AWS, Google Cloud Platform
- **Resumo do Perfil:** Profissional de tecnologia com 5 anos de experiência em desenvolvimento de software e análise de dados, buscando ingressar no curso de Pós-Graduação em Ciência de Dados e Inteligência Artificial
- **Perguntas sugeridas:**
  - Como você aplicaria suas habilidades em machine learning e big data em projetos de desenvolvimento de software?
  - Descreva sua experiência com equipes ágeis e como você contribuiu para a entrega de projetos em cloud
  - Como você lidou com desafios técnicos em seus projetos anteriores e quais foram as soluções implementadas?
- **Pontos fortes (ou Alinhamentos):**
  - Experiência em desenvolvimento de software e análise de dados
  - Conhecimento em linguagens de programação e frameworks relevantes
  - Familiaridade com serviços de nuvem e ferramentas de visualização de dados
  - Certificações em nuvem e áreas relacionadas à engenharia de software
- **Pontos a desenvolver (ou Desalinhamentos):**
  - Necessidade de aprofundar conhecimentos em Ciência de Dados e Inteligência Artificial
  - Possível necessidade de melhorar habilidades de comunicação e trabalho em equipe
- **Pontos de atenção:**
  - Verificar a compatibilidade das habilidades e experiência do candidato com as necessidades específicas da vaga
  - Avaliar a capacidade do candidato de trabalhar em equipe e colaborar com outros profissionais
- **Conclusão e recomendações:** Recomendo seguir com a entrevista para avaliar melhor as habilidades e experiência do candidato, além de discutir como ele pode contribuir para a equipe de desenvolvimento da empresa

## Calculando um score

In [63]:
prompt_score = """
Com base na vaga específica, calcule a pontuação final (de 0.0 a 10.0).
O retorno para esse campo deve conter apenas a pontuação final (x.x) sem mais nenhum texto ou anotação.
Seja justo e rigoroso ao atribuir as notas. A nota 10.0 só deve ser atribuída para candidaturas que superem todas as expectativas da vaga.

Critérios de avaliação:
1. Experiência (Peso: 35% do total): Análise de posições anteriores, tempo de atuação e similaridade com as responsabilidades da vaga.
2. Habilidades Técnicas (Peso: 25% do total): Verifique o alinhamento das habilidades técnicas com os requisitos mencionados na vaga.
3. Educação (Peso: 15% do total): Avalie a relevância da graduação/certificações para o cargo, incluindo instituições e anos de estudo.
4. Pontos Fortes (Peso: 15% do total): Avalie a relevância dos pontos fortes (ou alinhamentos) para a vaga.
5. Pontos Fracos (Desconto de até 10%): Avalie a gravidade dos pontos fracos (ou desalinhamentos) para a vaga.
"""

In [64]:
prompt_template = ChatPromptTemplate.from_template("""
Você é um especialista em Recursos Humanos com vasta experiência em análise de currículos.
Sua tarefa é analisar o conteúdo a seguir e extrair os dados conforme o formato abaixo, para cada um dos campos.
Responda apenas com o JSON estruturado e utilize somente essas chaves. Cuide para que os nomes das chaves sejam exatamente esses.
Não adicione explicações ou anotações fora do JSON.
Schema desejado:
{schema}

---
Para o cálculo do campo score:
{prompt_score}

---

Currículo a ser analisado:
'{cv}'

---

Vaga que o candidato está se candidatando:
'{job}'

""")
prompt_template

ChatPromptTemplate(input_variables=['cv', 'job', 'prompt_score', 'schema'], input_types={}, partial_variables={}, messages=[HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['cv', 'job', 'prompt_score', 'schema'], input_types={}, partial_variables={}, template="\nVocê é um especialista em Recursos Humanos com vasta experiência em análise de currículos.\nSua tarefa é analisar o conteúdo a seguir e extrair os dados conforme o formato abaixo, para cada um dos campos.\nResponda apenas com o JSON estruturado e utilize somente essas chaves. Cuide para que os nomes das chaves sejam exatamente esses.\nNão adicione explicações ou anotações fora do JSON.\nSchema desejado:\n{schema}\n\n---\nPara o cálculo do campo score:\n{prompt_score}\n\n---\n\nCurrículo a ser analisado:\n'{cv}'\n\n---\n\nVaga que o candidato está se candidatando:\n'{job}'\n\n"), additional_kwargs={})])

In [65]:
schema = """
{
  "name": "Nome completo do candidato",
  "area": "Área ou setor principal onde o candidato atua. Classifique em apenas uma: Desenvolvimento, Marketing, Vendas, Financeiro, Administrativo, Outros",
  "summary": "Resumo objetivo sobre o perfil profissional do candidato",
  "skills": ["competência 1", "competência 2", "..."],
  "education": "Resumo da formação acadêmica mais relevante",
  "interview_questions": ["Pelo menos 3 perguntas úteis para entrevista com base no currículo, para esclarecer algum ponto ou explorar melhor"],
  "strengths": ["Pontos fortes e aspectos que indicam alinhamento com o perfil ou vaga desejada"],
  "areas_for_development": ["Pontos que indicam possíveis lacunas, fragilidades ou necessidades de desenvolvimento"],
  "important_considerations": ["Observações específicas que merecem verificação ou cuidado adicional"],
  "final_recommendations": "Resumo avaliativo final com sugestões de próximos passos (ex: seguir com entrevista, indicar para outra vaga)",
  "score": 0.0
}
"""

fields = [
    "name",
    "area",
    "summary",
    "skills",
    "education",
    "interview_questions",
    "strengths",
    "areas_for_development",
    "important_considerations",
    "final_recommendations",
    "score"
]

## Conclusão e Funções finais

```text
Parâmetros:
- schema: estrutura de dados esperada no resultado
- job_details: informações da vaga
- prompt_template: template do prompt LangChain
- prompt_score: instrução adicional que influencia a avaliação do CV
- llm: instância do modelo de linguagem (LangChain)

Retorna:
- output: resposta bruta do LLM
- res: resposta formatada com base no schema
```

In [66]:
def parse_doc(file_path):
  from docling.document_converter import DocumentConverter

  converter = DocumentConverter()
  result = converter.convert(file_path)
  content = result.document.export_to_markdown()
  return content

In [67]:
def process_cv(schema, job_details, prompt_template, prompt_score, llm, file_path):
  if file_path:
    if not os.path.exists(file_path):
      raise FileNotFoundError(f"Arquivo não encontrado: {file_path}")

  content = parse_doc(file_path)

  chain = prompt_template | llm
  output = chain.invoke({"schema": schema, "cv": content, "job": job_details, "prompt_score": prompt_score})

  res = format_res(output.content)

  return output, res

In [71]:
file_cv = "/home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/notebooks/Currículo1.pdf"
output, res = process_cv(schema, job_details, prompt_template, prompt_score, llm, file_cv)
structured_data = parse_res_llm(res, fields)
structured_data

[INFO] 2026-06-28 20:09:53,465 [RapidOCR] base.py:23: Using engine_name: onnxruntime
[INFO] 2026-06-28 20:09:53,612 [RapidOCR] download_file.py:60: File exists and is valid: /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_det_small.onnx
[INFO] 2026-06-28 20:09:53,613 [RapidOCR] main.py:63: Using /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_det_small.onnx
[INFO] 2026-06-28 20:09:53,729 [RapidOCR] base.py:23: Using engine_name: onnxruntime
[INFO] 2026-06-28 20:09:53,735 [RapidOCR] download_file.py:60: File exists and is valid: /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-06-28 20:09:53,736 [RapidOCR] main.py:63: Using /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-06-28 20:09:53,782 [RapidOCR] base.py:23: Using engine_name: onnxruntime
[INFO] 2026-06-28 20:09:53,797 [RapidOCR] download_file.py:60: File exists and is valid: /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_rec_small.onnx
[INFO] 2026-06-28 20:09:53,798 [RapidOCR] main.py:63: Using /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_rec_small.onnx

Loading weights:   0%|          | 0/770 [00:00<?, ?it/s]

{'name': 'Thomas A. Anderson',
 'area': 'Desenvolvimento',
 'summary': 'Profissional de tecnologia com 5 anos de experiência em desenvolvimento de software e análise de dados, com habilidades técnicas em Python, JavaScript, SQL e frameworks como React, Node.js e Django.',
 'skills': ['Python',
  'JavaScript',
  'SQL',
  'React',
  'Node.js',
  'Django',
  'Power BI',
  'Git',
  'Docker',
  'AWS',
  'Google Cloud Platform'],
 'education': 'Bacharelado em Ciência da Computação pela Universidade de São Paulo (USP) com TCC em Otimização de Algoritmos de Machine Learning',
 'interview_questions': ['Como você lidou com desafios de escalabilidade em projetos anteriores?',
  'Pode descrever sua experiência com metodologias ágeis e como elas contribuíram para o sucesso dos projetos?',
  'De que forma você acredita que sua formação em Ciência da Computação e experiência em análise de dados podem ser aplicadas em nossa empresa?'],
 'strengths': ['Experiência em desenvolvimento de aplicações web full-stack',
  'Conhecimento em análise de dados e visualização de dados com Power BI',
  'Certificações relevantes em nuvem e engenharia de software'],
 'areas_for_development': ['Aprofundar conhecimentos em machine learning e big data para aplicar em projetos futuros',
  'Desenvolver habilidades de liderança para gerenciar equipes de desenvolvimento'],
 'important_considerations': ['Verificar a adequação das habilidades técnicas do candidato às necessidades específicas da vaga',
  'Avaliar a capacidade do candidato de trabalhar em equipe e colaborar com outros departamentos'],
 'final_recommendations': 'O candidato apresenta um perfil técnico forte e experiência relevante em desenvolvimento de software e análise de dados. Recomenda-se prosseguir com a entrevista para avaliar melhor as habilidades interpessoais e alinhamento com a cultura da empresa.',
 'score': 8.5}

In [73]:
file_cv = "/home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/notebooks/Currículo3.pdf"
output, res = process_cv(schema, job_details, prompt_template, prompt_score, llm, file_cv)
structured_data = parse_res_llm(res, fields)
structured_data

[INFO] 2026-06-28 20:16:53,578 [RapidOCR] base.py:23: Using engine_name: onnxruntime
[INFO] 2026-06-28 20:16:53,586 [RapidOCR] download_file.py:60: File exists and is valid: /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_det_small.onnx
[INFO] 2026-06-28 20:16:53,587 [RapidOCR] main.py:63: Using /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_det_small.onnx
[INFO] 2026-06-28 20:16:53,618 [RapidOCR] base.py:23: Using engine_name: onnxruntime
[INFO] 2026-06-28 20:16:53,620 [RapidOCR] download_file.py:60: File exists and is valid: /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-06-28 20:16:53,620 [RapidOCR] main.py:63: Using /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-06-28 20:16:53,650 [RapidOCR] base.py:23: Using engine_name: onnxruntime
[INFO] 2026-06-28 20:16:53,665 [RapidOCR] download_file.py:60: File exists and is valid: /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_rec_small.onnx
[INFO] 2026-06-28 20:16:53,666 [RapidOCR] main.py:63: Using /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_rec_small.onnx

Loading weights:   0%|          | 0/770 [00:00<?, ?it/s]

{'name': 'Alex Costa',
 'area': 'Desenvolvimento',
 'summary': 'Profissional multidisciplinar com 5 anos de experiência em design, desenvolvimento front-end e estratégias de marketing digital, buscando aprimorar habilidades em design de interfaces complexas e explorar soluções criativas.',
 'skills': ['Figma',
  'React.js',
  'Vue.js',
  'JavaScript',
  'HTML/CSS',
  'Node.js',
  'Firebase',
  'Google Analytics',
  'SEO',
  'WordPress',
  'Shopify'],
 'education': 'Bacharelado em Design Digital pela Universidade Federal do Paraná (UFPR) e Curso Técnico em Marketing Digital pelo Instituto de Tecnologia e Design (ITEDE)',
 'interview_questions': ['Como você aborda a criação de design systems para aplicações escaláveis?',
  'Descreva sua experiência com React.js e Vue.js em projetos anteriores',
  'Como você garantiria a acessibilidade e usabilidade em uma aplicação web?'],
 'strengths': ['Experiência em design e desenvolvimento front-end',
  'Conhecimento em ferramentas de marketing digital',
  'Habilidades em trabalho em equipe e colaboração'],
 'areas_for_development': ['Experiência limitada em back-end e desenvolvimento full stack',
  'Falta de conhecimento em Python e Django',
  'Necessidade de aprimorar habilidades em serviços de nuvem'],
 'important_considerations': ['Avaliar a capacidade do candidato de aprender e se adaptar a novas tecnologias',
  'Verificar a experiência em trabalhar em equipe e colaborar com outros profissionais'],
 'final_recommendations': 'O candidato apresenta habilidades valiosas em design e desenvolvimento front-end, mas carece de experiência em back-end e desenvolvimento full stack. Recomenda-se uma entrevista para avaliar melhor as habilidades e a capacidade de aprender e se adaptar.',
 'score': 7.5}

## Salvando no JSON

In [74]:
def save_json_cv(new_data, path_json, key_name="name"):
  if os.path.exists(path_json):
    with open(path_json, "r", encoding="utf-8") as f:
      data = json.load(f)
  else:
    data = []

  if isinstance(data, dict):
    data = [data]

  candidates = [entry.get(key_name) for entry in data]
  if new_data.get(key_name) in candidates:
    print(f"Currículo '{new_data.get(key_name)}' já registrado. Ignorando")
    return

  data.append(new_data)
  with open(path_json, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

In [80]:
# somente para teste

path_json = "curriculos.json"

save_json_cv(structured_data, path_json)

Currículo 'Alex Costa' já registrado. Ignorando

In [81]:
def display_json_table(path_json):
  with open(path_json, "r", encoding="utf-8") as f:
    data = json.load(f)

  df = pd.json_normalize(data)
  return df

df = display_json_table(path_json)
display(df)

,name,area,summary,skills,education,interview_questions,strengths,areas_for_development,important_considerations,final_recommendations,score
0,Alex Costa,Desenvolvimento,Profissional multidisciplinar com 5 anos de ex...,"[Figma, React.js, Vue.js, JavaScript, HTML/CSS...",Bacharelado em Design Digital pela Universidad...,[Como você aborda a criação de design systems ...,[Experiência em design e desenvolvimento front...,[Experiência limitada em back-end e desenvolvi...,[Avaliar a capacidade do candidato de aprender...,O candidato apresenta habilidades valiosas em ...,7.5

In [ ]:
# Caso algum candidato não tenha score calculado devido ao uso de algum valor antigo de variável, apagar arquivo e rodar novamente para cada currículo

path = "/home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/notebooks/Currículo3.pdf"
output, res = process_cv(schema, job_details, prompt_template, prompt_score, llm, path)
structured_data = parse_res_llm(res, fields)
save_json_cv(structured_data, path_json)

df = display_json_table(path_json)
display(df)

[INFO] 2026-06-28 20:41:44,678 [RapidOCR] base.py:23: Using engine_name: onnxruntime
[INFO] 2026-06-28 20:41:44,685 [RapidOCR] download_file.py:60: File exists and is valid: /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_det_small.onnx
[INFO] 2026-06-28 20:41:44,685 [RapidOCR] main.py:63: Using /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_det_small.onnx
[INFO] 2026-06-28 20:41:44,713 [RapidOCR] base.py:23: Using engine_name: onnxruntime
[INFO] 2026-06-28 20:41:44,716 [RapidOCR] download_file.py:60: File exists and is valid: /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-06-28 20:41:44,716 [RapidOCR] main.py:63: Using /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-06-28 20:41:44,746 [RapidOCR] base.py:23: Using engine_name: onnxruntime
[INFO] 2026-06-28 20:41:44,759 [RapidOCR] download_file.py:60: File exists and is valid: /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_rec_small.onnx
[INFO] 2026-06-28 20:41:44,760 [RapidOCR] main.py:63: Using /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_rec_small.onnx

Loading weights:   0%|          | 0/770 [00:00<?, ?it/s]

Currículo 'Alex Costa' já registrado. Ignorando

,name,area,summary,skills,education,interview_questions,strengths,areas_for_development,important_considerations,final_recommendations,score
0,Alex Costa,Desenvolvimento,Profissional multidisciplinar com 5 anos de ex...,"[Figma, React.js, Vue.js, JavaScript, HTML/CSS...",Bacharelado em Design Digital pela Universidad...,[Como você aborda a criação de design systems ...,[Experiência em design e desenvolvimento front...,[Experiência limitada em back-end e desenvolvi...,[Avaliar a capacidade do candidato de aprender...,O candidato apresenta habilidades valiosas em ...,7.5
1,Thomas A. Anderson,Desenvolvimento,Profissional de tecnologia com 5 anos de exper...,"[Python, JavaScript, SQL, React, Node.js, Djan...",Bacharelado em Ciência da Computação pela Univ...,[Como você aborda a otimização de algoritmos d...,[Experiência em desenvolvimento de software e ...,[Aprofundar conhecimentos em machine learning ...,[Verificar a profundidade do conhecimento em P...,Recomenda-se seguir com a entrevista para aval...,8.5
2,Ana Clara Santos,Desenvolvimento,Desenvolvedora full stack com 4 anos de experi...,"[React, Vue.js, TypeScript, Tailwind CSS, Node...",Bacharelado em Sistemas de Informação pela Pon...,[Como você aborda a otimização de performance ...,"[Experiência em desenvolvimento de software, C...",[Aprofundamento em Power BI ou outras ferramen...,[Verificar a adequação das habilidades técnica...,Recomenda-se seguir com a entrevista para aval...,8.5

In [85]:
df[["name", "score", "summary"]]

,name,score,summary
0,Alex Costa,7.5,Profissional multidisciplinar com 5 anos de ex...
1,Thomas A. Anderson,8.5,Profissional de tecnologia com 5 anos de exper...
2,Ana Clara Santos,8.5,Desenvolvedora full stack com 4 anos de experi...

## Interface com Streamlit

In [86]:
!pip install -q streamlit python-dotenv
# Somente usado para Google Colab
!npm install -q localtunnel

9111.06s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

9116.89s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹
up to date, audited 23 packages in 1s
⠹
⠹3 packages are looking for funding
⠹  run `npm fund` for details
⠹
2 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
⠹

In [87]:
%%writefile utils_proj03.py
import os
from docling.document_converter import DocumentConverter
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate, HumanMessagePromptTemplate, MessagesPlaceholder
import json
import pandas as pd
import csv
import streamlit as st

def load_llm(id_model, temperature):
  llm = ChatGroq(
      model=id_model,
      temperature=temperature,
      max_tokens=None,
      timeout=None,
      max_retries=2,
  )
  return llm


def format_res(res, return_thinking=False):
  res = res.strip()

  if return_thinking:
    res = res.replace("<think>", "[pensando...] ")
    res = res.replace("</think>", "\n---\n")

  else:
    if "</think>" in res:
      res = res.split("</think>")[-1].strip()

  return res


def parse_doc(file_path):
  converter = DocumentConverter()
  result = converter.convert(file_path)
  content = result.document.export_to_markdown()
  return content


def parse_res_llm(response_text: str, required_fields: list) -> dict:
    try:
        # Remove a parte do raciocínio (<think>...</think>)
        if "</think>" in response_text:
            response_text = response_text.split("</think>")[-1].strip()

        # Localiza o JSON e faz o parsing
        start_idx = response_text.find('{')
        end_idx = response_text.rfind('}') + 1
        if start_idx == -1 or end_idx == 0:
            raise json.JSONDecodeError("Nenhum JSON encontrado na resposta", response_text, 0)

        json_str = response_text[start_idx:end_idx]
        info_cv = json.loads(json_str)

        for field in required_fields:
            if field not in info_cv:
                info_cv[field] = []

        return info_cv

    except json.JSONDecodeError:
        #Erro ao interpretar a resposta do modelo
        return


def save_json_cv(new_data, path_json, key_name="name"):
    # Carrega o JSON existente, se houver
    if os.path.exists(path_json):
        with open(path_json, "r", encoding="utf-8") as f:
            data = json.load(f)
    else:
        data = []

    if isinstance(data, dict):
        data = [data]

    # Verifica se já existe um currículo com o mesmo nome
    candidates = [entry.get(key_name) for entry in data]
    if new_data.get(key_name) in candidates:
        st.warning(f"Currículo '{new_data.get(key_name)}' já registrado. Ignorando.")
        return

    # Adiciona e salva
    data.append(new_data)
    with open(path_json, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def load_json_cv(path_json):
    with open(path_json, "r", encoding="utf-8") as f:
        return json.load(f)


def show_cv_result(result: dict):
    md = f"### 📄 Análise e Resumo do Currículo\n"
    if "name" in result:
        md += f"- **Nome:** {result['name']}\n"
    if "area" in result:
        md += f"- **Área de Atuação:** {result['area']}\n"
    if "skills" in result:
        md += f"- **Competências:** {', '.join(result['skills'])}\n"
    if "summary" in result:
        md += f"- **Resumo do Perfil:** {result['summary']}\n"
    if "interview_questions" in result:
        md += f"- **Perguntas sugeridas:**\n"
        md += "\n".join([f"  - {q}" for q in result["interview_questions"]]) + "\n"
    if "strengths" in result:
        md += f"- **Pontos fortes (ou Alinhamentos):**\n"
        md += "\n".join([f"  - {s}" for s in result["strengths"]]) + "\n"
    if "areas_for_development" in result:
        md += f"- **Pontos a desenvolver (ou Desalinhamentos):**\n"
        md += "\n".join([f"  - {a}" for a in result["areas_for_development"]]) + "\n"
    if "important_considerations" in result:
        md += f"- **Pontos de atenção:**\n"
        md += "\n".join([f"  - {i}" for i in result["important_considerations"]]) + "\n"
    if "final_recommendations" in result:
        md += f"- **Conclusão e recomendações:** {result['final_recommendations']}\n"
    return md


def save_job_to_csv(data, filename):
    headers = ['title', 'description', 'details']
    file_exists = os.path.exists(filename)

    with open(filename, 'a', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=headers, delimiter=';')
        if not file_exists:
            writer.writeheader()
        writer.writerow(data)


def load_job(csv_path):
  try:
    df = pd.read_csv(csv_path, sep=';', encoding='utf-8')
    job = df.iloc[-1]
    prompt_text = f"""
    **Vaga para {job['title']}**

    **Descrição da Vaga:**
    {job['description']}

    **Detalhes Completos:**
    {job['details']}
    """

    return prompt_text.strip()

  except FileNotFoundError:
    return "Erro: Arquivo de vagas não encontrado"

def process_cv(schema, job_details, prompt_template, prompt_score, llm, file_path):

  if file_path:
    if not os.path.exists(file_path):
      raise FileNotFoundError(f"Arquivo não encontrado: {file_path}")

  content = parse_doc(file_path)

  chain = prompt_template | llm
  output = chain.invoke({"schema": schema, "cv": content, "job": job_details, "prompt_score": prompt_score})

  res = format_res(output.content)

  return output, res


def display_json_table(path_json):
  with open(path_json, "r", encoding="utf-8") as f:
    data = json.load(f)

  df = pd.DataFrame(data)
  return df

Writing utils_proj03.py

In [99]:
%%writefile app03.py
import streamlit as st
import uuid
from utils_proj03 import *
from dotenv import load_dotenv
load_dotenv()

st.set_page_config(page_title="Triagem e Análise de Currículos", page_icon="📄", layout="wide")

id_model = "llama-3.3-70b-versatile"
temperature = 0.7
json_file = 'curriculos.json'
path_job_csv = "vagas.csv"

llm = load_llm(id_model, temperature)

job = {}
job['title'] = "Desenvolvedor(a) Full Stack"
job['description'] = "Estamos em busca de um(a) Desenvolvedor(a) Full Stack para integrar o time de tecnologia da nossa empresa, atuando em projetos estratégicos com foco em soluções escaláveis e orientadas a dados. O(a) profissional será responsável por desenvolver, manter e evoluir aplicações web robustas, além de colaborar com times multidisciplinares para entregar valor contínuo ao negócio."
job['details'] = """
Atividades:
- Desenvolver e manter aplicações web em ambientes modernos, utilizando tecnologias back-end e front-end.
- Trabalhar com equipes de produto, UX e dados para entender demandas e propor soluções.
- Criar APIs, integrações e dashboards interativos.
- Garantir boas práticas de versionamento, testes e documentação.
- Participar de revisões de código, deploys e melhorias contínuas na arquitetura das aplicações.

Pré-requisitos:
- Sólidos conhecimentos em Python, JavaScript e SQL.
- Experiência prática com frameworks como React, Node.js e Django.
- Familiaridade com versionamento de código usando Git.
- Experiência com serviços de nuvem, como AWS e Google Cloud Platform.
- Capacidade de trabalhar em equipe, com boa comunicação e perfil colaborativo.

Diferenciais:
- Conhecimento em Power BI ou outras ferramentas de visualização de dados.
- Experiência anterior em ambientes ágeis (Scrum, Kanban).
- Projetos próprios, contribuições open source ou portfólio técnico disponível.
- Certificações em nuvem ou áreas relacionadas à engenharia de software.
"""

schema = """
{
  "name": "Nome completo do candidato",
  "area": "Área ou setor principal que o candidato atua. Classifique em apenas uma: Desenvolvimento, Marketing, Vendas, Financeiro, Administrativo, Outros",
  "summary": "Resumo objetivo sobre o perfil profissional do candidato",
  "skills": ["competência 1", "competência 2", "..."],
  "education": "Resumo da formação acadêmica mais relevante",
  "interview_questions": ["Pelo menos 3 perguntas úteis para entrevista com base no currículo, para esclarecer algum ponto ou explorar melhor"],
  "strengths": ["Pontos fortes e aspectos que indicam alinhamento com o perfil ou vaga desejada"],
  "areas_for_development": ["Pontos que indicam possíveis lacunas, fragilidades ou necessidades de desenvolvimento"],
  "important_considerations": ["Observações específicas que merecem verificação ou cuidado adicional"],
  "final_recommendations": "Resumo avaliativo final com sugestões de próximos passos (ex: seguir com entrevista, indicar para outra vaga)",
  "score": 0.0
}
"""

fields = [
    "name",
    "area",
    "summary",
    "skills",
    "education",
    "interview_questions",
    "strengths",
    "areas_for_development",
    "important_considerations",
    "final_recommendations",
    "score"
]

prompt_score = """
Com base na vaga específica, calcule a pontuação final (de 0.0 a 10.0).
O retorno para esse campo deve conter apenas a pontuação final (x.x) sem mais nenhum texto ou anotação.
Seja justo e rigoroso ao atribuir as notas. A nota 10.0 só deve ser atribuída para candidaturas que superem todas as expectativas da vaga.

Critérios de avaliação:
1. Experiência (Peso: 35% do total): Análise de posições anteriores, tempo de atuação e similaridade com as responsabilidades da vaga.
2. Habilidades Técnicas (Peso: 25% do total): Verifique o alinhamento das habilidades técnicas com os requisitos mencionados na vaga.
3. Educação (Peso: 15% do total): Avalie a relevância da graduação/certificações para o cargo, incluindo instituições e anos de estudo.
4. Pontos Fortes (Peso: 15% do total): Avalie a relevância dos pontos fortes (ou alinhamentos) para a vaga.
5. Pontos Fracos (Desconto de até 10%): Avalie a gravidade dos pontos fracos (ou desalinhamentos) para a vaga.
"""

prompt_template = ChatPromptTemplate.from_template("""
Você é um especialista em Recursos Humanos com vasta experiência em análise de currículos.
Sua tarefa é analisar o conteúdo a seguir e extrair os dados conforme o formato abaixo, para cada um dos campos.
Responda apenas com o JSON estruturado e utilize somente essas chaves. Cuide para que os nomes das chaves sejam exatamente esses.
Não adicione explicações ou anotações fora do JSON.
Schema desejado:
{schema}

---
Para o cálculo do campo score:
{prompt_score}

---

Currículo a ser analisado:
'{cv}'

---

Vaga que o candidato está se candidatando:
'{job}'

""")

if "uploader_key" not in st.session_state:
  st.session_state.uploader_key = str(uuid.uuid4())

if "selected_cv" not in st.session_state:
  st.session_state.selected_cv = None

# Salva descrição da vaga em um .csv
save_job_to_csv(job, path_job_csv)
job_details = load_job(path_job_csv)

col1, col2 = st.columns(2)
with col1:
  st.header("Triagem e Análise de Currículos")
  st.markdown("#### Vaga: {}".format(job["title"]))
with col2:
  uploaded_file = st.file_uploader("Envie um currículo em PDF", type=["pdf"], key=st.session_state.uploader_key)

if uploaded_file is not None:
  with st.spinner("Analisando o currículo..."):
    path = uploaded_file.name
    with open(path, "wb") as f:
      f.write(uploaded_file.read())

    output, res = process_cv(schema, job_details, prompt_template, prompt_score, llm, path)
    structured_data = parse_res_llm(res, fields)
    save_json_cv(structured_data, path_json=json_file, key_name="name")

    st.success("Currículo analisado com sucesso!")
    st.session_state.uploader_key = str(uuid.uuid4())

  st.write(show_cv_result(structured_data))

  with st.expander("Ver dados estruturados (JSON)"):
    st.json(structured_data)

if os.path.exists(json_file):
  st.subheader("Lista de currículos analisados", divider="gray")
  df = display_json_table(json_file)
  for i, row in df.iterrows():
    cols = st.columns([1, 3, 1, 5])
    with cols[0]:
      if st.button("Ver detalhes", key = f"btn_{i}"):
        st.session_state.selected_cv = row.to_dict()
    with cols[1]:
        st.write(f"**Nome:** {row.get('name', '-')}")
    with cols[2]:
        st.write(f"**Score:** {row.get('score', '-')}")
    with cols[3]:
        st.write(f"**Resumo:** {row.get('summary', '-')}")

if st.session_state.selected_cv:
  st.markdown("-----")
  st.write(show_cv_result(st.session_state.selected_cv))

  with st.expander("Ver dados estruturados (JSON)"):
    st.json(st.session_state.selected_cv)

if os.path.exists(json_file):
  with open(json_file, "r", encoding="utf-8") as f:
    json_data = f.read()
  st.download_button(
      label = "📥 Baixar arquivo .json",
      data = json_data,
      file_name = json_file,
      mime="application/json"
  )

  df = display_json_table(json_file)
  st.dataframe(df)

Overwriting app03.py

In [101]:
!streamlit run app03.py

# somente para google colab
# !wget -q -O - ipv4.icanhazip.com
# !npx localtunnel --port 8501

12271.09s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

2026-06-28 21:41:07.151 Uvicorn server started on 0.0.0.0:8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.0.71:8501

The plugin langchain_docling will not be loaded because Docling is being executed with allow_external_plugins=false.
The plugin langchain_docling will not be loaded because Docling is being executed with allow_external_plugins=false.
[INFO] 2026-06-28 21:41:39,335 [RapidOCR] base.py:23: Using engine_name: onnxruntime
[INFO] 2026-06-28 21:41:39,344 [RapidOCR] download_file.py:60: File exists and is valid: /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_det_small.onnx
[INFO] 2026-06-28 21:41:39,344 [RapidOCR] main.py:63: Using /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_det_small.onnx
[INFO] 2026-06-28 21:41:39,382 [RapidOCR] base.py:23: Using engine_name: onnxruntime
[INFO] 2026-06-28 21:41:39,383 [RapidOCR] download_file.py:60: File exists and is valid: /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-06-28 21:41:39,383 [RapidOCR] main.py:63: Using /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-06-28 21:41:39,417 [RapidOCR] base.py:23: Using engine_name: onnxruntime
[INFO] 2026-06-28 21:41:39,429 [RapidOCR] download_file.py:60: File exists and is valid: /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_rec_small.onnx
[INFO] 2026-06-28 21:41:39,429 [RapidOCR] main.py:63: Using /home/jpmaida/Documents/git/AI-Expert-Academy/LLMs-e-Agentes-de-AI-para-Empresas-e-Neg-cios/.venv/lib/python3.11/site-packages/rapidocr/models/PP-OCRv6_rec_small.onnx
The plugin langchain_docling will not be loaded because Docling is being executed with allow_external_plugins=false.
Loading weights: 100%|████████████████████| 770/770 [00:00<00:00, 16745.90it/s]
The plugin langchain_docling will not be loaded because Docling is being executed with allow_external_plugins=false.
  Stopping...
^C
  Stopping...